### ISSUE TITLE
regression in #982

### ISSUE THREAD

**Issue by jschmid1** [SUSE/DeepSea#1032]
### Description of Issue/Question

https://github.com/SUSE/DeepSea/pull/982 introduced version checking with https://github.com/SUSE/DeepSea/pull/982/files#diff-006352bf138477d37689ad5f3edb5e5bR764

If the package 'ceph-common' is not installed on that minion salt returns a struct:

``` python
{'mon1.ceph': False}
```
which leads to a exception when invoking:

``` python
if info and 'version' in info[minion]['ceph-common']:
``` 

as
``` python
False
```
has not k/v subscription.

Error:

``` python
*** TypeError: 'bool' object is not subscriptable

```

**Comment by smithfarm** [comment]
not sure it's a regression since the only thing that changed in that line was `s/ceph/ceph-common/`
