### ISSUE TITLE
Add tags to the project

### ISSUE THREAD

**Issue by jschmid1** [SUSE/DeepSea#1057]
### Description of Issue/Question

We should add tags to the [project description ](https://blog.github.com/2017-01-31-introducing-topics/)

That will probably increase our visibility

**Comment by jschmid1** [comment]
Only admins can do that. Summoning @l-mb @denisok

**Comment by denisok** [comment]
I am not an admin for this repo

**Comment by jschmid1** [comment]
then it's probably @l-mb

**Comment by jschmid1** [comment]
@alexandergraul can do that now also

**Comment by jschmid1** [comment]
Possbile tags:


- Ceph
- Ceph-deployment
- Salt
- Distributed-Storage
- Software-defined-Storage
- Deployment

more?

**Comment by alexandergraul** [comment]
Done
