### ISSUE TITLE
Use pylint or any other linter for syntax checks

### ISSUE THREAD

**Issue by theanalyst** [SUSE/DeepSea#107]
As we're adding more and more code in the runner, we tend to error, a linter should be able to catch many of them, though at this moment we need a lot more code style fixes before we can have a linter run clean. 

We could use salt-pylint and borrow salt's own pylintrc config which should allow us to not report syntax errors on things salt monkey patches in the global namespace (for eg `__salt__` and `__opts__` builtins to name a few)

cc @rjfd @jschmid1 @swiftgist @jan--f

**Comment by jschmid1** [comment]
+1 to use `salt-pylint`. there are some custom things that the default pylint will forbid.

**Comment by jan--f** [comment]
I'm in favour of this too. I'd put it rather low on the priority list for now though. Maybe after the next release would be a good time. salt-pylint seems like a good idea to me.

**Comment by smithfarm** [comment]
We're already running tox, right? It's trivial to configure it to run flake8.

**Comment by jan--f** [comment]
How about this suggestion: Lets keep make new code conform the [PEP8 guidline](https://www.python.org/dev/peps/pep-0008/). Its easy enough to do, there lint plugins for editors, linters for cli, auto-formatters and its fairly widely used.
This should start to convert the code base and we can decide if its worth to clean up existing code later.

**Comment by jschmid1** [comment]
+1 

whenever we touch code, let's just make it PEP8 conform.

**Comment by rjfd** [comment]
I think that's a good plan, although I also think that we should really fix the existing code because it would be much easier to avoid introducing bugs when making changes to existing code.

**Comment by swiftgist** [comment]
My question is how absolute is the enforcement?  Extraneous spaces? Fine.  Trying to line up long lines to make the linter happy? Not so much.  And I also thought unit tests prevented introducing new bugs and  that a linter will not give you that much mileage.

**Comment by theanalyst** [comment]
currently we don't cover much in terms of runner modules, and it is easy to make mistakes like calling a class function without self or say making a typo in calling a function (we've had a few of these) and the only way we can  currently get them is by using the respective functionality in runner and see if salt throws a traceback, this is something a linter would trivially catch

**Comment by smithfarm** [comment]
The advantage of strict coding style enforcement in a largish development team is that it quickly gets everyone writing code in the same style.

The disadvantage, of course, is that one has to abandon old habits.

**Comment by jan--f** [comment]
I'm ok with a best effort approach. Better then nothing.

**Comment by BlaineEXE** [comment]
+1  to `salt-pylint`.
+1 to @smithfarm's comment. The goal for all of this is code that is easy to read, write, and maintain, and the PEP8 standard is ubiquitous for Python (by definition).

**Comment by swiftgist** [comment]
@theanalyst Are we creating PR's and relying on pylint without verifying that the runners work?

I am fine with best effort, but is the introduction of the linter advisory or absolute?  And to what degree?  Are people suggesting a 10/10?  If not, then what?

**Comment by rjfd** [comment]
> @theanalyst Are we creating PR's and relying on pylint without verifying that the runners work?

@swiftgist that is not what @theanalyst said. Currently there is not much coverage of existing code with unit tests, and therefore having pylint would help with untested code. Of course, when we develop a PR we also test it locally with whatever means we have at hand.

linters are tools to help developers to use a uniform coding style and also give alerts on syntatic errors.
Since currently, a lot of code is not in conformance with PEP8, we should not enforce that our PRs must be warning free from pylint

**Comment by swiftgist** [comment]
> Since currently, a lot of code is not in conformance with PEP8, we should not enforce that our PRs must > be warning free from pylint

Then, that is fine.

**Comment by theanalyst** [comment]
Adding to what @rjfd said, what I meant is more in the lines of linters can catch code errors much easier than humans do, and it would at least give us a base promise of stuff like we're using something without importing or using a variable that isn't in the namespace etc which are a source of subtle bugs that can only be caught at runtime otherwise

**Comment by BlaineEXE** [comment]
What about cyclomatic complexity analysis? I personally think it is a valuable metric for suggesting when code may be too complex to approach for new contributors. It seems pylint lacks cyclomatic complexity analysis, but we could configure flake8 to check for this (optionally disabling flake8's other checks).
