### ISSUE TITLE
E: Unable to locate package golang-github-prometheus-node_exporter 

### ISSUE THREAD

**Issue by joalmjoalm** [SUSE/DeepSea#1088]
### Description of Issue/Question
Ubuntu 16.04 minion during stage 2
salt-minion version 2016.11.04

deepsea version on master: deepsea 0.8.2+git.0.6b39c2648

Error on minion during stage 2: Unable to locate package golang-github-prometheus-node_exporter

Ubuntu package available as prometheus-node-exporter

See distro friendly init.sls #998

In order to adress os-specific package names, cant you had a os-specific config yml file where each specific os-term is specified in a os-specific yml-file. Then I can choose to launch w ubuntu, suse or cent yml. Instead of having conditional clauses in the code for different os-specific name-standards on cmd,files or packages etc . 
Move the switching to an external os-specific yml and keeping the code to handle the logic which could of course maybe also be os-specific, but then code is focused on logic and not on switching config-data.

If so I could have myself switched packaged name from golang-github-prometheus-node_exporter to prometheus-node-exporter.

Just an idea instead of hardcode config-data and get into much conditional clauses. 3-4 os-specific yml files and referencing that file would have been enough.

**Comment by swiftgist** [comment]
That's the goal in general.  The conditional clauses would be in the init.sls and we hope to have the common distros addressed.  On the chance that the your distro/os/version is missing, but another fits the bill, you could still override that pillar variable to choose the one you want.  (So, the default should work, but anticipate that it won't and keep the friction to customize low.)

Currently, that's not there and the friction to make a change is annoying, but doable.  

***
The separate issue with prometheus and grafana is that we had a deadline so the standard init.sls is not present throughout the /srv/salt/ceph/monitoring tree.

Also, #998 is planned for the current master, but no discussion on backporting this to the 0.8 series.  If you tried master on Salt 2016.11.04 and had failures, we think we know where the conversion from python2 to python3 also replaced the 'expr_form' with 'target_type' caused the incompatibility.  We should be able to centralize that call and stay compatible on master with Salt 2016.11.
