### ISSUE TITLE
Travis checks are gone

### ISSUE THREAD

**Issue by jschmid1** [SUSE/DeepSea#1128]
### Description of Issue/Question

Github changed the way how checks work.

https://blog.github.com/2018-05-07-introducing-checks-api/

For Travis:

https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com

It got extended quite a bit.. probably worth looking at some new features we may use.

**Comment by alexandergraul** [comment]
The new API (currently in public beta) is for Github Applications. As of now, only Travis CI is an interesting GH-App supporting this new feature. To make use of it, we need add the [Travis App](https://github.com/marketplace/travis-ci/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW43MA==#pricing-and-setupl)

**Comment by jschmid1** [comment]
replaced by internal jenkins
