### ISSUE TITLE
chown on job cache introduces significant lag in some cases

### ISSUE THREAD

**Issue by tserong** [SUSE/DeepSea#1131]
https://github.com/SUSE/DeepSea/pull/1078 fixes permissions on the salt job cache, but due to (effectively) a `chown -R` being run after several individual steps in each stage, we end up with some rather long waits, for example:

````
# salt-run state.orch ceph.stage.2
[WARNING ] Skipping empty file /srv/pillar/ceph/stack/ceph/cluster.yml
deepsea_minions          : valid
yaml_syntax              : valid
profiles_populated       : valid
public network           : 172.16.1.0/24
cluster network          : 172.16.2.0/24
admin.ceph_master:
  Name: push.proposal - Function: salt.runner - Result: Changed Started: - 09:11:49.399839 Duration: 492.493 ms
  Name: refresh_pillar1 - Function: salt.state - Result: Changed Started: - 09:11:49.892456 Duration: 1465.488 ms
  Name: advise.networks - Function: salt.runner - Result: Changed Started: - 09:11:51.358052 Duration: 1043.896 ms
  Name: admin key - Function: salt.state - Result: Changed Started: - 09:11:52.402255 Duration: 540.973 ms
  Name: osd key - Function: salt.state - Result: Changed Started: - 09:11:52.943495 Duration: 540.186 ms
  Name: mon key - Function: salt.state - Result: Changed Started: - 09:11:53.483924 Duration: 562.055 ms
  Name: mgr key - Function: salt.state - Result: Changed Started: - 09:11:54.046228 Duration: 51695.188 ms
  Name: igw key - Function: salt.state - Result: Changed Started: - 09:12:45.741680 Duration: 51802.932 ms
  Name: mds key - Function: salt.state - Result: Changed Started: - 09:13:37.544888 Duration: 52964.688 ms
  Name: rgw key - Function: salt.state - Result: Changed Started: - 09:14:30.509918 Duration: 52868.998 ms
  Name: ganesha key - Function: salt.state - Result: Changed Started: - 09:15:23.379178 Duration: 53421.292 ms
  Name: openattic key - Function: salt.state - Result: Changed Started: - 09:16:16.800708 Duration: 748.261 ms
  Name: setup monitoring - Function: salt.state - Result: Changed Started: - 09:16:17.549380 Duration: 102815.046 ms
  Name: install and setup node exporters - Function: salt.state - Result: Clean Started: - 09:18:00.364754 Duration: 29718.991 ms

Summary for admin.ceph_master
-------------
Succeeded: 14 (changed=13)
Failed:     0
-------------
Total states run:     14
Total run time:  400.680 s
````

That's 400 seconds (six-seven minutes) for stage 2. About four and a half of those minutes are taken up by mgr, igw, mds, rgw and ganesha key generation, because each of those key generation states does that file permission change on the job cache. That permission change also happens as part of `setup monitoring`; a subsequent test showed that of the ~100 seconds for that state, ~70 were spent on the job cache permissions. Is it feasible to move this permissions change somehow so that it only happens once in stage 2, rather than six times?

**Comment by swiftgist** [comment]
Hmm, I wonder if a `find /var/cache/salt/master/jobs -user root -exec chown salt:salt {} \;` would outperform the file.directory.

Since this is only a problem on the master, maybe we could move this out of the Stages entirely.  This could be a Salt engine with a specific purpose.  Activate with inotify and block on itself not to rerun more than necessary.  It's still a kludge but would not add times to the stages.
