### ISSUE TITLE
engulf and ceph.conf

### ISSUE THREAD

**Issue by swiftgist** [SUSE/DeepSea#1139]
### Description of Issue/Question
Great plans go awry.  The engulf processes attempts to convert a non-DeepSea cluster into a DeepSea configured cluster without altering the existing Ceph cluster.  It's a tall order.  The implementation is incomplete and will likely remain partially manual.  Automating unusual or unexpected manual Ceph configurations is difficult.  One of these we chose not to automate is importing the ceph.conf.

The engulf creates a copy of the existing ceph.conf, places it in /srv/salt/ceph/configuration/files and sets the configuration_init to default-import.  All of this is fine.  The issue is that engulfed clusters are somewhat uncommon.  The result is confused administrators following the normal directions for making changes to ceph.conf (i.e. add something to /srv/salt/ceph/configuration/ceph.conf.d/global.conf), running `salt 'admin*' state.apply ceph.configuration.create`, seeing the intended result in /srv/salt/ceph/configuration/cache, but then running `salt 'admin*' state.apply ceph.configuration` does not push out your changes because DeepSea is using the imported ceph.conf.  When this does not jump to mind, enabling debugging on the minion and finding a single line in a noisy log is the only recourse.

The simplest solution is to print a bold white message at the end of Stage 2 that the configuration_init is set to default-import.  The message should encourage the conversion of the imported ceph.conf and unsetting this pillar variable.

***
For those reading and asking is it really necessary to use the standard ceph.conf split file strategy.  The entire restart logic is based on the changes to these files.  If an admin wishes to use a single file, then the restarts of all Ceph components will not work by default and other adjustments will be needed.

**Comment by Martin-Weiss** [comment]
Could we enhance the engulf for the ceph.conf to split the existing ceph.conf and put it in the places where the restart logic and other configuration parts rely on?
(i.e. take the rgw config part and place it in rgw.conf etc.)

**Comment by tserong** [comment]
No, not really. Splitting arbitrary ceph.conf files into the correct pieces to match DeepSea's ceph.conf.d structure would be difficult to get right in general, and impossible to guarantee that we didn't miss something that would end up wrecking some existing user's unexpectedly bizarre config file.
