### ISSUE TITLE
Rescind: Set "mon_allow_pool_delete" to true for deletion of pools

### ISSUE THREAD

**Issue by supriti** [SUSE/DeepSea#115]
For stage 5, the pools will not be deleted if mon_allow_pool_delete is false. 
Error EPERM: pool deletion is disabled; you must first set the mon_allow_pool_delete config option to true before you can destroy a pool

Set this variable to true globally.

**Comment by swiftgist** [comment]
This can be added to ceph.conf.d/global.conf.... but probably shouldn't.  

The other discussion is creating a utility that uses mon injection to temporarily allow pool deletion, deletes the pool(s), reverts the change and is used in conjunction with disengage.safety.
