### ISSUE TITLE
Enable deploying collectd on all cluster nodes, to gather performance data on a central node

### ISSUE THREAD

**Issue by LenzGr** [SUSE/DeepSea#116]
In order to be able to monitor and observe the cluster nodes' general performance, it would be helpful if DeepSea would deploy collectd on all nodes. These collectd instance should be configured to remotely log to a central (definable) collectd instance. By default, this could be the management node directly.

**Comment by swiftgist** [comment]
Since we have gone the Prometheus route, I will close this.  Although if somebody wishes to have collectd in DeepSea, I have no objections to re-opening/opening a new issue.
