### ISSUE TITLE
Salt has a tendency to quickly fill up the /var/cache/salt/master/jobs directory

### ISSUE THREAD

**Issue by capri1989** [SUSE/DeepSea#1176]
Salt has a tendency to quickly fill up the /var/cache/salt/master/jobs directory, so would it be possible to add some kind of automatism to stage.0 which removes and cleans up this directory?

**Comment by jschmid1** [comment]
@capri1989 
to my knowledge this gets cleaned automatically by salt.


> 
> A number of options are available when configuring the job cache. The default caching system uses local storage on the Salt Master and can be found in the job cache directory (on Linux systems this is typically /var/cache/salt/master/jobs). The default caching system is suitable for most deployments as it does not typically require any further configuration or management.
> 
> The default job cache is a temporary cache and jobs will be stored for 24 hours. If the default cache needs to store jobs for a different period the time can be easily adjusted by changing the keep_jobs parameter in the Salt Master configuration file. The value passed in is measured via hours:
> 
> `keep_jobs: 24`
> 

https://docs.saltstack.com/en/latest/topics/jobs/job_cache.html

Where do you see that? What size does this exceed?

Try:

`find . -ctime -1 | wc -l`

should yield a number > 0

`find . -ctime +2 | wc -l`

should yield 0

**Comment by jschmid1** [comment]
maybe also `du -hcs /var/cache/salt/master/jobs`

**Comment by jschmid1** [comment]
backported with #1214
