### ISSUE TITLE
populate.py missing StringIO import needed by engulf

### ISSUE THREAD

**Issue by tserong** [SUSE/DeepSea#1183]
https://github.com/SUSE/DeepSea/blob/master/srv/modules/runners/populate.py#L1294 says:

````
cp.readfp(StringIO("\n".join([line.strip() for line in ceph_conf.split("\n")])))
````

But, https://github.com/SUSE/DeepSea/blob/master/srv/modules/runners/populate.py#L60-L61 says:

````
# notused
#from cStringIO import StringIO
````

I suspect this needs to be changed to:

````
from io import StringIO
````

Note that I haven't tested this to verify, just opening this immediately upon noticing the potential problem. I'll verify/confirm/fix a bit later.

**Comment by tserong** [comment]
...or, `cp.readfp(StringIO(...)` could maybe be replaced with `cp.read_string(...)`, thus dispensing with the need for the import.

**Comment by jschmid1** [comment]
What's the status or this?

**Comment by tserong** [comment]
Not done yet (~nextish on my list)
