### ISSUE TITLE
unreliable scsi symlinks

### ISSUE THREAD

**Issue by swiftgist** [SUSE/DeepSea#1203]
### Description of Issue/Question
With #952 and #1061, DeepSea started selecting other symlinks.  However, the udev rules from 58-scsi-sg3_symlink.rules do not create persistent and unique names.  On hardware with these devices, zapping an OSD causes the device name to be given to another device.

"I obviously cannot choose the wine in front of you" - Vizzini, Princess Bride

After examining 58-scsi-sg3_symlink.rules and 60-persistent-storage.rules, I believe there is no reason to use any of the `scsi-` prefixed names.  The most reliable symlink would be the `scsi-3` prefixed devices but these are redundant with `wwn-0x` devices.

Rather than have complicated logic including or excluding particular expressions of devices, removing the `scsi-` prefix entirely will simplify the entire process.  For any hardware that has an `ata-` prefix, that will get chosen.  Otherwise, the `wwn` will be selected.

**Comment by Martin-Weiss** [comment]
Is there a bug open on the 58-scsi-sg3_symlink.rules issue? 
If that is not creating persistent and unique names why does that exist at all?

**Comment by swiftgist** [comment]
While trying to gather more information about this issue, I am mixed about a practical solution.  Nothing guarantees that scsi-S names will be unique.  In practice though, the 60-persistent-storage rules seem to be.  

With regards to DeepSea 0.8.4 preferring the device name with the most underscores may only be a problem on Azure.  I really do not have enough data.  However, if that's the case, it seems bad form to force all users to use the worse case common denominator of `wwn`.

I closed the above PR when I thought of adding a conditional to check for RAID devices and only restrict names then.  (BTW, RAID devices are *not* recommended for Ceph.  Some hardware vendors only sell servers with RAID and the configurations are set to JBOD or similar.)  

Asking admins to tweak udev rules or somehow select between good ones and bad ones seems a bit much.  Keeping with the DeepSea style of providing a default and easily selecting others would be one solution, but we would need to rearrange some code to make that trivial.  Also, this would be unique compared to all other DeepSea subdirectories.  (The current ones are related to some Ceph functionality or management.  This would be specifically about configuration preferences.)

**Comment by swiftgist** [comment]
The default seems to work well for many, but we may always have environments that are impossible to predict.  I am creating a PR that allows an admin to override the arguments to the find command via the pillar.  I believe this structure will be suitable for other modules if we should need them.

To override the default match expression of `-name ata* -o -name scsi* -o -name nvme*`, add the following to the pillar:

```
ceph:
  modules:
    cephdisks:
      device:
        match: '-name wwn*'
```

To override the default pathname of `/dev/disk/by-id`, add the following to the pillar:

```
ceph:
  modules:
    cephdisks:
      device:
        pathname: '/dev/disk/by-label'
```
