### ISSUE TITLE
proposal.generate sorting

### ISSUE THREAD

**Issue by swiftgist** [SUSE/DeepSea#1215]
### Description of Issue/Question
The current yaml files generated by Stage 1 are pseudo random.  As a result, regenerating a configuration may result in devices appearing in a different order.  For standalone Filestore and Bluestore configurations, this does not matter.  For split Filestore and Bluestore configurations, the new configuration is valid, but a migration may be necessary.

One suggestion from a couple of discussions is to sort the devices based on the `/dev/disk/by-path` entries.  That would prevent accidental shuffling for disk replacements.

**Comment by denisok** [comment]
@jan--f @jschmid1 what are your thoughts on this?

**Comment by jschmid1** [comment]
> One suggestion from a couple of discussions is to sort the devices based on the /dev/disk/by-path entries. That would prevent accidental shuffling for disk replacements.

This is what the discussions resulted in. The downside of this approach is that a user will have to do initial migrations(probably) after changing to the new sorting scheme.

**Comment by jan--f** [comment]
I believe the profile generation should be deterministic, i.e. all things equal the code should spit out identical profiles.

What is the situation where profiles would be regenerated? Would that be with the same hardware? Are we talking about changing profiles for OSD replacement?

For the latter it might be better to change the existing profiles where necessary. The yaml files can easily be loaded into python objects and then altered and dumped again. In my head that should be straight forward, though I'm not sure regarding the use case.

**Comment by jschmid1** [comment]
```
proposal.populate ( runner )
  -> proposal.generate ( module )
    -> cephdisks.list
      -> hwinfo/lshw
```

That would mean; **If** the profile generation is deterministic we currently rely on the hwinfo/lshw output to be sorted.
By looking at a simple hwinfo output ( `hwinfo --only disk` [example](http://paste.opensuse.org/86078068) ) I assume that the internal sorting is done by looking at the _Storage Controller #_ . 

Looking at a more sophisticated cluster, things are different and hwinfo does not seem to sort by _Storage Controller #_ 

Next step is to have a look at the hwinfo implementation and check how / if it's sorted.

**Comment by jschmid1** [comment]
Things change if attached to a rais bus controller..

**Comment by jschmid1** [comment]
I added a test that tries to figure out how the module behaves with unsorted input.

**Comment by jschmid1** [comment]
If this however not assert as true we have to go the other route, like @jan--f already stated, to read-in the moved 'profile-replaced' file and make sure that the newly generated proposal matches the old layout and wal-db matching.

How this will work out is to be seen..

**Comment by jschmid1** [comment]
The mentioned test seems to prove that `proposal.generate` might be deterministic, but is depending on the ordering from it's input function ( cephdisks.list -> hwinfo )

**Comment by jschmid1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Adapting "replacement procedure"](https://trello.com/c/QwcfG4jd/11-adapting-replacement-procedure)
