### ISSUE TITLE
salt-api and runner authentication

### ISSUE THREAD

**Issue by swiftgist** [SUSE/DeepSea#122]
I recently learned that runner authentication seems to fail.  The example from https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#usage for the runner portion of the example does not work.  While I did not find the root cause, the problem starts with /usr/lib/python2.7/site-packages/salt/master.py line 1521 "good = check_fun(..." in Salt 2015.8.12.  Considering our current eauth settings allow 'admin' to do anything, I do not believe that the issue is configuration related.

To explore the functionality of executing runners in the salt-api, adding "good = True" directly after this line allows all runners that I tried to work.

**Comment by rjfd** [comment]
@swiftgist have you gave permission for the user `admin` to call runner modules?
If not add ` - '@runner'` to the list of permission for the user in `eauth.conf`

I've tested the call of runner modules in my setup and it works. For instance I run the populate runner like this:

```
curl -i http://host:port -H 'X-Auth-Token: token-string' -d fun='populate.proposals' -d client='runner'
```

**Comment by swiftgist** [comment]
That was it.  Thanks.
