### ISSUE TITLE
Exercise stage.5 ( removal ) in functional/system tests

### ISSUE THREAD

**Issue by jschmid1** [SUSE/DeepSea#1237]
### Description of Issue/Question

After hitting a bug in stage.5 it's time to create a test to exercise the code in stage.5

Potential issues:
  - Teuthology only deploys _one_ node which can't be removed without bringing down the cluster.

**Comment by jschmid1** [comment]
> The functional tests should be divided into different orchestrations according to what (minimal) cluster configuration is required to run them.

if that's feasible; awesome!

**Comment by smithfarm** [comment]
Another thing to keep in mind is that these orchestration files are running a number of test cases, in sequence, on a single cluster. That means special care has to be taken that each test case tears itself down correctly so it doesn't influence the test cases that follow it.

Tests that are very important should have their own orchestration files, to ensure they run in a fresh cluster.

**Comment by smithfarm** [comment]
> if that's feasible; awesome!

The orchestration files would need to reflect the minimum cluster configuration needed. So functional tests requiring no more than a single node could be placed in an orchestration named, e.g. "ceph.functests.1node". Ones that need at least two nodes could be in "ceph.functests.2nodes" etc.

**Comment by smithfarm** [comment]
(This would be a good opportunity to rename: ceph.smoketests -> ceph.functests to reflect that these are real functional tests, not just smoke tests.)
