### ISSUE TITLE
ceph mds: Default PG_NUM should be calculated based on user selection

### ISSUE THREAD

**Issue by supriti** [SUSE/DeepSea#124]
For mds pool creation, srv/salt/ceph/mds/pools/default.sls, currently we use as default 256.
But from previous stages, we already have enough information to calculate a right PG num

We should use the calculated value instead of default 256.

**Comment by jan--f** [comment]
I agree that 256 is a bit too high as a default. I'd argue against calculating a good value though. It adds complexity and effort on default values that in a lot of cases won't be used.

Imho we should set 128 as a default. This is the minimal recommended pg_count and can be easily increased.

**Comment by swiftgist** [comment]
That's fine.  I think I used the originally example there.

**Comment by jan--f** [comment]
I created #132. @supriti what do you think about creating a card in the [discussion index](https://github.com/SUSE/DeepSea/projects/2) to keep track of your idea. I'd like to see this too but I think right now we need to prioritize other feature.

**Comment by supriti** [comment]
Done. https://github.com/SUSE/DeepSea/projects/2#card-1994169 
 Closing this issue now.
