### ISSUE TITLE
Unable to change 'proposal.populate' via 'salt-run'

### ISSUE THREAD

**Issue by drkrieger01** [SUSE/DeepSea#1240]
### Description of Issue/Question
When trying to run the command: "salt-run proposal.populate format=filestore journal_size=100G", I get the following output: 
ceph-01:~ # salt-run proposal.populate format=filestore journal_size=100G
[WARNING ] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.
[WARNING ] not overwriting existing proposal ceph-02.XXXXXXXX.com
[WARNING ] not overwriting existing proposal ceph-03.XXXXXXXX.com
[WARNING ] not overwriting existing proposal ceph-01.XXXXXXXX.com
{'G@deepsea:*': {'data': 0,
                 'db-ratio': 5,
                 'db-size': '500m',
                 'encryption': '',
                 'format': 'bluestore',
                 'journal': 0,
                 'journal-size': '5g',
                 'leftovers': False,
                 'name': 'default',
                 'nvme-spinner': False,
                 'nvme-ssd': False,
                 'nvme-ssd-spinner': False,
                 'ratio': 5,
                 'ssd-spinner': False,
                 'standalone': False,
                 'wal': 0,
                 'wal-size': '500m'}}

I've never used Deepsea to do a Ceph setup before, but I figured I'd give it a try in order to use the web interface. I'm following the instructions on Openattic's website: https://openattic.readthedocs.io/en/latest/install_guides/quick_start_guide.html

I'm running this command after doing the 'ceph.stage.1' in order to modify the config in a much quicker simpler fashion. If I'm understanding this wrong, please let me know.

Things I've tried: 
1. chmod the 'dmidecode' file to the salt user/group
2. made sure the config file was using the right user account (root or 'salt')
3. Completely wiped and reloaded all three nodes in this config

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Not sure where to get this info?

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Follow instructions on this webpage: https://openattic.readthedocs.io/en/latest/install_guides/quick_start_guide.html

When you've completed the command for 'ceph.stage.1', run this command:

`salt-run proposal.populate format=filestore journal_size=100G` 

### Versions Report
Salt Version:
`Version: 0.8.2+git.0.6b39c2648`

rpm Salt-Minion:
`Name        : salt-minion
Version     : 2016.11.4
Release     : 8.1
Architecture: x86_64
Install Date: Wed Jul 25 13:40:29 2018
Group       : System/Management
Size        : 37807
License     : Apache-2.0
Signature   : RSA/SHA256, Mon Aug  7 05:01:24 2017, Key ID b88b2fd43dbdc284
Source RPM  : salt-2016.11.4-8.1.src.rpm
Build Date  : Mon Aug  7 05:00:15 2017
Build Host  : cloud125
Relocations : (not relocatable)
Packager    : http://bugs.opensuse.org
Vendor      : openSUSE
URL         : http://saltstack.org/
Summary     : The client component for Saltstack
Description :
Salt minion is queried and controlled from the master.
Listens to the salt master and execute the commands.
Distribution: openSUSE Leap 42.3`

rmp Salt-Master:
`Name        : salt-master
Version     : 2016.11.4
Release     : 8.1
Architecture: x86_64
Install Date: Wed Jul 25 13:40:29 2018
Group       : System/Management
Size        : 1662854
License     : Apache-2.0
Signature   : RSA/SHA256, Mon Aug  7 05:01:24 2017, Key ID b88b2fd43dbdc284
Source RPM  : salt-2016.11.4-8.1.src.rpm
Build Date  : Mon Aug  7 05:00:15 2017
Build Host  : cloud125
Relocations : (not relocatable)
Packager    : http://bugs.opensuse.org
Vendor      : openSUSE
URL         : http://saltstack.org/
Summary     : The management component of Saltstack with zmq protocol supported
Description :
The Salt master is the central server to which all minions connect.
Enabled commands to remote systems to be called in parallel rather
than serially.
Distribution: openSUSE Leap 42.3`

**Comment by jschmid1** [comment]
Hey @drkrieger01

> [WARNING ] not overwriting existing proposal ceph-02.XXXXXXXX.com
> [WARNING ] not overwriting existing proposal ceph-03.XXXXXXXX.com
> [WARNING ] not overwriting existing proposal ceph-01.XXXXXXXX.com

That's the key information here. It already created a 'default' proposal after completing stage.1 for you which can be found under /srv/pillar/ceph/proposal/profile-default.

If you now run `salt-run proposal.populate format=filestore journal_size=100G` ( notice that no name= is provided ) it will fall back to the 'default' namespace. As we don't allow overwriting, you will see these warnings above.

Try to append a 'name=xxx' to your command like so:

`salt-run proposal.populate format=filestore journal_size=100G name=test1`

and adapt your policy.cfg accordingly.


hth

**Comment by drkrieger01** [comment]
Thanks for the tip @jschmid1 ! 
It sort of helped... but didn't really work. The yml files at /profile-test1/stack/default/ceph/minions/ now only show three lines instead of the entire drive listings:
`ceph:
  storage:
    osds: {}`
When I ran the command, it still gave me the 'dmidecode' error, and gave me nothing on the output to indicate that the variables had been modified:
`ceph-01:~ # salt-run proposal.populate format=filestore journal=1 nvme-spinner=True journal-size=100G name=test1
[WARNING ] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.
{}
True
ceph-01:~ #'
So instead of trying the quick and easy method, I decided to edit the 'default' yml files to match what I needed. Example:
`ceph:
  storage:
    osds:
      /dev/disk/by-id/scsi-35000c500b0603a2c:
        encryption: ''
        format: filestore
        journal: /dev/disk/by-id/-SAMSUNG_MZ1LV960HCJH-000MU_S2C2NX0J224624
        journal_size: 100G
      /dev/disk/by-id/scsi-35000c500b063157b:
        encryption: ''
        format: filestore
        journal: /dev/disk/by-id/-SAMSUNG_MZ1LV960HCJH-000MU_S2C2NX0J224624
        journal_size: 100G
      /dev/disk/by-id/scsi-35000c500b0632f65:
        encryption: ''
        format: filestore
        journal: /dev/disk/by-id/-SAMSUNG_MZ1LV960HCJH-000MU_S2C2NX0J224624
        journal_size: 100G
      /dev/disk/by-id/scsi-35000c500b065da5f:
        encryption: ''
        format: filestore
        journal: /dev/disk/by-id/-SAMSUNG_MZ1LV960HCJH-000MU_S2C2NX0J224624
        journal_size: 100G`

However, when I do this and run "salt-run  proposal.peek", it spits out the original default. 
What would the command be to point the 'peek' at the name=test1? I tried: 
`salt-run proposal.peek name=test1`
But this didn't work, simply showed me the original untouched default as well. 
I then modified the 'test1' folders scripts to the updated default scripts and tried the peek again:
`ceph-01:~ # salt-run proposal.peek test1
[WARNING ] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.
Exception occurred in runner proposal.peek: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
TypeError: peek() takes exactly 0 arguments (290 given)
ceph-01:~ # salt-run proposal.peek name=test1
[WARNING ] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.
{'ceph-02.arthomson.com': {'/dev/disk/by-id/-SAMSUNG_MZ1LV960HCJH-000MU_S2C2NX0J224614': {'format': 'bluestore'},
                           '/dev/disk/by-id/ata-ST4000DM004-2CV104_ZFN0ZE92': {'format': 'bluestore'},
                           '/dev/disk/by-id/ata-ST4000DM004-2CV104_ZFN17GA9': {'format': 'bluestore'},
                           '/dev/disk/by-id/ata-ST4000DM004-2CV104_ZFN19SHD': {'format': 'bluestore'},
                           '/dev/disk/by-id/ata-ST4000DM004-2CV104_ZFN19SPN': {'format': 'bluestore'}}}
{'ceph-03.arthomson.com': {'/dev/disk/by-id/-SAMSUNG_MZ1LV960HCJH-000MU_S2C2NX0J224646': {'format': 'bluestore'},
                           '/dev/disk/by-id/ata-ST4000DM004-2CV104_ZFN17GSX': {'format': 'bluestore'},
                           '/dev/disk/by-id/ata-ST4000DM004-2CV104_ZFN17JWN': {'format': 'bluestore'},
                           '/dev/disk/by-id/ata-ST4000DM004-2CV104_ZFN19NQ1': {'format': 'bluestore'},
                           '/dev/disk/by-id/ata-ST4000DM004-2CV104_ZFN19SWV': {'format': 'bluestore'}}}
{'ceph-01.arthomson.com': {'/dev/disk/by-id/-SAMSUNG_MZ1LV960HCJH-000MU_S2C2NX0J224624': {'format': 'bluestore'},
                           '/dev/disk/by-id/scsi-35000c500b0603a2c': {'format': 'bluestore'},
                           '/dev/disk/by-id/scsi-35000c500b063157b': {'format': 'bluestore'},
                           '/dev/disk/by-id/scsi-35000c500b0632f65': {'format': 'bluestore'},
                           '/dev/disk/by-id/scsi-35000c500b065da5f': {'format': 'bluestore'}}}
None'
As you can see, I wasn't sure on the arguments to use with peek so I tried both with and without "name=". The second one spits out the original untouched default configs. What am I doing wrong?

**Comment by jschmid1** [comment]
> When I ran the command, it still gave me the 'dmidecode' error, and gave me nothing on the output to indicate that the variables had been modified:

 You can safely ignore the dmidecode error. This is a bug in salt and only occurs in virtual environments.



> and gave me nothing on the output to indicate that the variables had been modified:
> ceph-01:~ # salt-run proposal.populate format=filestore journal=1 nvme-spinner=True journal-size=100G name=test1

There should be a directory under /srv/pillar/ceph/proposals with the name 'profiles-test1'

The workflow for the 'proposal' runner was intended like this:


experiment with the proposal.peek method until you got the results you are happy with. i.e.

`salt-run proposal.peek format=bluestore nvme-spinner=True db_size=5G`

then you can actually write the configuration to disk with

`salt-run proposal.populate format=bluestore nvme-spinner=True db_size=5G`



note: you are trying to configure filestore which is not the default anymore. If you don't have good reasons to go with filestore, I'd recommend you to stick with bluestore.

**Comment by jschmid1** [comment]
Inactive
