### ISSUE TITLE
engulf does not fill profile import and does not use persistent names for scsi devices

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/DeepSea#1264]
### Description of Issue/Question
After an engulf of an existing SES 4 cluster the profile-import yml files are empty - just one has a single OSD in and that is using non-persistent device names

### Setup
Admin on SES 5 and cluster on SES 4. Patches applied up to end of august 2018

### Steps to Reproduce Issue
engulf an existing ses 4 cluster
Hint: we have dell hardware with RAID 0 setup for all HDDs.

### Versions Report
0.8.5

**Comment by jschmid1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug 1104773 - "type" file is missing in /var/lib/ceph/osd/ceph-*/ after upgrading SES step by step to SES 4 causing engulf to fail in creation of OSD proposal yml files](https://trello.com/c/N906DSp7/3-bug-1104773-type-file-is-missing-in-var-lib-ceph-osd-ceph-after-upgrading-ses-step-by-step-to-ses-4-causing-engulf-to-fail-in-cr)
