### ISSUE TITLE
deepsea command should also work with engulf

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/DeepSea#1265]
### Description of Issue/Question
when we use "deepsea stage run populate.engulf_existing_cluster" we get a strange python error "Import error: No module named six.moves" 

### Setup
engulf of an existing ses 4 cluster

### Steps to Reproduce Issue
execute  "deepsea stage run populate.engulf_existing_cluster"

### Versions Report
0.8.5

**Comment by tserong** [comment]
Leaving aside the strange import error, this can't work anyway -- populate.engulf_existing_cluster is a runner, not a stage, so you can't use `deepsea stage run` to invoke it, it's just `salt-run populate.engulf_existing_cluster`.
