### ISSUE TITLE
deepsea command fails in case python-six is not installed

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/DeepSea#1266]
### Description of Issue/Question
uninstall python-six or make sure it is not installed -> command will fail.

### Versions Report
deepsea 0.8.5

--> could we add a dependency on "python-six"?

**Comment by jschmid1** [comment]
* How and where did you see this? 

* Was this a rpm/make installation?

* Which deepsea command fails?

**Comment by Martin-Weiss** [comment]
> Am 15.08.2018 um 16:40 schrieb Joshua Schmid <notifications@github.com>:
> 
> How and where did you see this?
> 

From the top of my head I believe it was when they executed „deepsea stage run ceph.stage.0“ 
> Was this a rpm/make installation?

Yes
> Which deepsea command fails?
> 

See above.

I assume this can be reproduced by simply uninstalling python-six rpm.

**Comment by jschmid1** [comment]
I mean.. what's the reproducer for this? Need context

**Comment by Martin-Weiss** [comment]
> Am 15.08.2018 um 17:16 schrieb Joshua Schmid <notifications@github.com>:
> 
> I mean.. what's the reproducer for this? Need context
> 
the deepsea rpm is missing a dependency on the python-six rpm but deepsea uses code that depends on that.

In case you install a server that does not have python-six rpm installed - i.e.  due to the minimal setup for linux the admin wants to have - installing the deepsea rpm does not pull the required package in due to this missing dependency in the spec file (I assume).

Does that explain your question?

**Comment by jschmid1** [comment]
but that's based on assumptions?

**Comment by Martin-Weiss** [comment]
We could fix the problem with a zypper in python-six and then the problem was gone. So we know that the installation of the deepsea rpm did not install python-six and due to that we know that the dependency must be missing. We do not know why the dependency is missing so we assume it is due to a missing dependency in the deepsea rpm spec file.

**Comment by tserong** [comment]
````
# rpm -qa '*six*'
python-six-1.9.0-9.12.1.noarch

# zypper rm python-six
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 4 packages are going to be REMOVED:
  python-Twisted python-cryptography python-pyOpenSSL python-six

4 packages to remove.
After the operation, 27.3 MiB will be freed.
Continue? [y/n/...? shows all options] (y): y
(1/4) Removing python-Twisted-15.2.1-9.2.1.x86_64 ...............................................................................[done]
(2/4) Removing python-pyOpenSSL-16.0.0-4.3.4.noarch .............................................................................[done]
(3/4) Removing python-cryptography-1.3.1-7.6.1.x86_64 ...........................................................................[done]
(4/4) Removing python-six-1.9.0-9.12.1.noarch ...................................................................................[done]

# deepsea stage run ceph.stage.0
Traceback (most recent call last):
  File "/usr/bin/deepsea", line 9, in <module>
    load_entry_point('deepsea==0.8.5+44.ge26e728b5', 'console_scripts', 'deepsea')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/deepsea/__main__.py", line 10, in <module>
    from .deepsea import main
  File "/usr/lib/python2.7/site-packages/deepsea/deepsea.py", line 22, in <module>
    from .monitor import Monitor
  File "/usr/lib/python2.7/site-packages/deepsea/monitor.py", line 14, in <module>
    from six.moves import range
ImportError: No module named six.moves
````
