### ISSUE TITLE
Enable openATTIC services after installation

### ISSUE THREAD

**Issue by LenzGr** [SUSE/DeepSea#134]
This was raised in [BSC#1027261](https://bugzilla.suse.com/show_bug.cgi?id=1027261): after installing openATTIC, DeepSea should also ensure that the openATTIC background services `openattic-systemd` and `openattic-rpcd` are enabled for the next reboot.

We'll look into adding this to `oaconfig` as well, this is tracked in [OP-985](https://tracker.openattic.org/browse/OP-985).

**Comment by swiftgist** [comment]
#135 is in progress.

**Comment by LenzGr** [comment]
#135 was merged. #198 is a follow-up to this one.
