### ISSUE TITLE
['There are no files under the profiles directory. Probably an issue with the discovery stage.']

### ISSUE THREAD

**Issue by Hybelkaninen** [SUSE/DeepSea#1430]
### Description of Issue/Question
Trying to setup cluster on clean opensuse 42.3 leap with salt configured and working.
Stage 0 & 1 returned no errors but stage 2 says i have no profiles which is true, but what should i do about it?

alt '*' test.ping
cephmon01b:
    True
cephigw01b:
    True
cephigw02b:
    True
cephnode03b:
    True
cephmds02b:
    True
cephrgw01b.:
    True
cephmon03b:
    True
cephmon02b:
    True
cephnode01b:
    True
cephadmin01b:
    True
cephmds01b:
    True
cephnode02b:
    True
cephrgw02b:
    True

salt-run state.orch ceph.stage.2
[WARNING ] profile-default/cluster/*.sls matched no files
[WARNING ] profile-default/stack/default/ceph/minions/*.yml matched no files
[WARNING ] profile-default/cluster/*.sls matched no files
[WARNING ] profile-default/stack/default/ceph/minions/*.yml matched no files
deepsea_minions          : valid
yaml_syntax              : valid
profiles_populated       : ['There are no files under the profiles directory. Probably an issue with the discovery stage.']
[ERROR   ] No highstate or sls specified, no execution made
cephadmin01b_master:
----------
          ID: validate failed
    Function: salt.state
        Name: just.exit
      Result: False
     Comment: No highstate or sls specified, no execution made
     Started: 11:16:43.334373
    Duration: 0.681 ms
     Changes:   

Summary for cephadmin01b_master
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.681 ms

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
## Cluster Assignment
cluster-ceph/cluster/*.sls

policy.cfg (
## Roles
# ADMIN
role-master/cluster/cephadmin01b*.sls
role-admin/cluster/cephadmin*.sls

# MON
role-mon/cluster/cephmon*.sls

# MGR (mgrs are usually colocated with mons)
role-mgr/cluster/cephmon*.sls

# MDS
role-mds/cluster/cephmds*.sls

# IGW
role-igw/cluster/cephigw*.sls

# RGW
role-rgw/cluster/cephrgw*.sls

# NFS
role-ganesha/cluster/cephnode*.sls

# openATTIC
role-openattic/cluster/cephadmin01b*.sls

# COMMON
config/stack/default/global.yml
config/stack/default/ceph/cluster.yml

## Profiles
profile-default/cluster/*.sls
profile-default/stack/default/ceph/minions/*.yml
)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Not sure where to find

### Versions Report
(Provided by running:
`salt-run deepsea.version`
0.8.2+git.0.6b39c2648
`rpm -qi salt-minion`
Name        : salt-minion
Version     : 2016.11.4
Release     : 8.1
Architecture: x86_64
Install Date: Tue Oct 16 09:46:22 2018
Group       : System/Management
Size        : 37807
License     : Apache-2.0
Signature   : RSA/SHA256, Mon Aug  7 13:01:24 2017, Key ID b88b2fd43dbdc284
Source RPM  : salt-2016.11.4-8.1.src.rpm
Build Date  : Mon Aug  7 13:00:15 2017
Build Host  : cloud125
Relocations : (not relocatable)
Packager    : http://bugs.opensuse.org
Vendor      : openSUSE
URL         : http://saltstack.org/
Summary     : The client component for Saltstack
Description :
Salt minion is queried and controlled from the master.
Listens to the salt master and execute the commands.
Distribution: openSUSE Leap 42.3

`rpm -qi salt-master`
Name        : salt-master
Version     : 2016.11.4
Release     : 8.1
Architecture: x86_64
Install Date: Tue Oct 16 09:46:23 2018
Group       : System/Management
Size        : 1662854
License     : Apache-2.0
Signature   : RSA/SHA256, Mon Aug  7 13:01:24 2017, Key ID b88b2fd43dbdc284
Source RPM  : salt-2016.11.4-8.1.src.rpm
Build Date  : Mon Aug  7 13:00:15 2017
Build Host  : cloud125
Relocations : (not relocatable)
Packager    : http://bugs.opensuse.org
Vendor      : openSUSE
URL         : http://saltstack.org/
Summary     : The management component of Saltstack with zmq protocol supported
Description :
The Salt master is the central server to which all minions connect.
Enabled commands to remote systems to be called in parallel rather
than serially.
Distribution: openSUSE Leap 42.3
)

**Comment by callithea** [comment]
Hi @TechMeistro42, you need to create a file ``policy.cfg`` in /srv/pillcar/ceph/proposals - see https://github.com/SUSE/DeepSea/wiki/policy and https://github.com/SUSE/DeepSea/blob/master/doc/examples/policy.cfg-rolebased for examples.
The error ``There are no files under the profiles directory. Probably an issue with the discovery stage``could also mean that you do not have additional disks attached. Usually I have three additional disks attached per node (besides the OS disk) - hope this helps.

**Comment by TechMeistro42** [comment]
Hi @callithea,
i have now added a vm disk on cephnode01, 02 & 03.
I get following error now when rerunning stage 1:
[ERROR   ] Verify that targeted minions have proposal.generate
Thanks for the help

**Comment by jschmid1** [comment]
Since there is no action, I'd assume this is fixed. Please re-open if needed
