### ISSUE TITLE
DeepSea cannot install ceph in SLE-12-SP3

### ISSUE THREAD

**Issue by marcosps** [SUSE/DeepSea#1482]
### Description of Issue/Question
DeepSea fails to deploy a cluster when running in SLE-12-SP3

### Setup
vagrant-ceph using SLE-12-SP3 box

### Steps to Reproduce Issue
Execute all deepsea phases: prep, discovery, configure and deploy. Deploy will fail and complain that zypper command failed. When running ```zypper install ceph``` in any node, it returns a problem with some packages that need a downgrade, like bellow:

```
Problem: ceph-12.2.7+git.1531910353.c0ef85b854-2.21.1.x86_64 requires ceph-mds = 12.2.7+git.1531910353.c0ef85b854-2.21.1, but this requirement cannot be provided                              
  uninstallable providers: ceph-mds-12.2.7+git.1531910353.c0ef85b854-2.21.1.x86_64[Storage-update]                                                                                             
 Solution 1: Following actions will be done:
  downgrade of librados2-12.2.8+git.1536505967.080f2248ff-2.15.1.x86_64 to librados2-12.2.7+git.1531910353.c0ef85b854-2.21.1.x86_64                                                            
  downgrade of python-rados-12.2.8+git.1536505967.080f2248ff-2.15.1.x86_64 to python-rados-12.2.7+git.1531910353.c0ef85b854-2.21.1.x86_64                                                      
 Solution 2: do not install ceph-12.2.7+git.1531910353.c0ef85b854-2.21.1.x86_64
 Solution 3: break ceph-12.2.7+git.1531910353.c0ef85b854-2.21.1.x86_64 by ignoring some of its dependencies 
``` 

### Versions Report
deepsea: 0.8.6
salt-minion: 2016.11.4-46.7.1
salt-master: 2016.11.4-46.7.1

**Comment by jschmid1** [comment]
Sorry, but this is not a DeepSea problem, but a miss-configuration of repositories. There is nothing we can do about this.

**Comment by marcosps** [comment]
So, do I need to open a ticket in BZ?

**Comment by jschmid1** [comment]
Mh, someone that knows more about SUSE's dependency resolution and repo building system than me :>

**Comment by vidya-vidz** [comment]
Hi Marcosps, were you able to solve this issue? I am trying to install SUSE Enterprise Storage 6 and I get the same error while installing Ceph using deepsea.

**Comment by jschmid1** [comment]
> Hi Marcosps, were you able to solve this issue? I am trying to install SUSE Enterprise Storage 6 and I get the same error while installing Ceph using deepsea.

SES6 is not supported with SLE12-SP3. Please use SLES15-SP1
