### ISSUE TITLE
Stage 0: failed: Jinja error: 'validate.setup'

### ISSUE THREAD

**Issue by nagarashish** [SUSE/DeepSea#150]
Trying to run "salt-run state.orch ceph.stage.0" command get following error
OS:- CentOS7
Compile:- DeepSea

[CRITICAL] Rendering SLS 'base:ceph.stage.0.master.default' failed: Jinja error: 'validate.setup'
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
output = template.render(**decoded_context)
File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
return self.environment.handle_exception(exc_info, True)
File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
reraise(exc_type, exc_value, tb)
File "", line 3, in top-level template code
File "/usr/lib/python2.7/site-packages/salt/modules/saltutil.py", line 1181, in runner
return rclient.cmd(name, kwarg=kwargs, print_event=False, full_return=True)
File "/usr/lib/python2.7/site-packages/salt/runner.py", line 144, in cmd
full_return)
File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 225, in cmd
self.functions[fun], arglist, pub_data
File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1086, in getitem
func = super(LazyLoader, self).getitem(item)
File "/usr/lib/python2.7/site-packages/salt/utils/lazy.py", line 101, in getitem
raise KeyError(key)
KeyError: 'validate.setup'

; line 3

NOTE:  validate.py is present in /srv/modules/runners.

Any idea how to resolve this issue?  Is this framework built only for SUSE or can it work on Centos also?

**Comment by swiftgist** [comment]
Hi Nagarashish,
  The framework is intended to work for different Linux distributions; however, you may be the first to try it on CentOS.  The validate.setup is two small checks to ensure that a master_minion is defined in the Salt pillar and that your Ceph version is Jewel or later.  The complaint looks like Jinja is unhappy with the first line in /srv/salt/ceph/stage/0/master/default.sls.  

  Did you restart your salt-master after you installed DeepSea?  Or does the following work?

```
# salt-run validate.setup
```
You should get output similar to
```
master_minion            : valid
ceph_version             : valid
None
```

**Comment by nagarashish** [comment]
Yes restarted salt-master.  Getting 'validate.setup' not available when I run salt-run validate.setup on master.

**Comment by swiftgist** [comment]
Please reopen if this is still valid.

**Comment by marcosps** [comment]
I had the same issue, and running ```salt-run validate.setup``` and it returned ```'validate' __virtual__ returned False: No module named 'configobj'```. So, after installing python3-configobj, the problem was gone. I am using opensuse-leap 15.0.

**Comment by marcosps** [comment]
@nagarashish can you install python-configobj and then run ``` salt-run validate.setup  ``` again? I wrote a patch to fix this problem by installing this package for centos and opensuse.

**Comment by akha666** [comment]
I have the same issue with SUSE 15.1 and SES 6
```
ses-admin:~ # salt-run validate.setup
No minions matched the target. No command was sent, no jid was assigned.
No minions matched the target. No command was sent, no jid was assigned.
No minions matched the target. No command was sent, no jid was assigned.
No minions matched the target. No command was sent, no jid was assigned.
master_minion            : valid
ceph_version             : valid
openattic-disabled       : valid
salt_version             : valid
ceph_updates             : valid
salt_updates             : valid
deepsea_minions          : ['No minions matched for G@deepsea:* - See `man deepsea-minions`']
False

```
