### ISSUE TITLE
disks.py needs python3

### ISSUE THREAD

**Issue by lookcrabs** [SUSE/DeepSea#1554]
### Description of Issue/Question
/srv/modules/runners/disks.py uses python3 syntax. Saltstack Open needs python2.7 and fails to import the the module via py2.7. 

https://www.python.org/dev/peps/pep-3107/

```
[ERROR   ] Failed to import runners disks, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1555, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/srv/modules/runners/disks.py", line 63
    def __init__(self, drive_group_name, drive_group_values) -> None:
                                                             ^
SyntaxError: invalid syntax
[ERROR   ] Failed to import runners disks, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1555, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/srv/modules/runners/disks.py", line 63
    def __init__(self, drive_group_name, drive_group_values) -> None:
```
### Setup
Vanilla Ubuntu 18.04 vms with vanilla salt with salt-ssh installed to bootstrap nodes easier. 
root@cephfs-manager-01:~# salt --version
salt 2019.2.0 (Fluorine)

root@planx-cephfs-manager-01:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

### Steps to Reproduce Issue

```
 -- install latest version of saltstack
git clone https://github.com/SUSE/DeepSea.git
make install 
-- install minion on all nodes
salt '*' grains.append deepsea default
salt-run state.orch ceph.stage.0
```

### Versions Report
(Provided by running:
`salt-run deepsea.version`
 -- bombs but shows `0.9.13+17.g0b7eb45d`
`rpm -qi salt-minion`
    2019.2.0+ds-1
`rpm -qi salt-master`
    2019.2.0+ds-1 
)

**Comment by jschmid1** [comment]
Hey @lookcrabs.

thanks for reporting. Version v0.9.x requires python3 entirely. Since salt2019.x (and 2018) already fully supports python3, I'd suggest you to switch to it.
