### ISSUE TITLE
`freedisks` reference

### ISSUE THREAD

**Issue by BlaineEXE** [SUSE/DeepSea#157]
File `srv/salt/ceph/mines/files/mine_functions.conf` has line `freedisks.list: []` but I don't see `freedisks` anywhere else in the codebase. There is also a commented-out reference in `srv/modules/runners/populate.py`. Are these vestigial remnants, or am I missing something?

**Comment by swiftgist** [comment]
freedisks.py was the predecessor to cephdisks.py.  It's currently living in srv/salt/ceph/_modules/examples.  It can be removed from the mine_functions.conf.  I kept it around since the code is simpler and a bit easier to explain/show somebody what salt mines are.

**Comment by swiftgist** [comment]
BTW, are you getting an empty list from

salt '*' mine.get 'data*' cephdisks.list

with the current master?

**Comment by jschmid1** [comment]
Just tried it; empty list. 

Although this should not be harmful, I see a warning in the minion logs:

2017-03-22 08:41:07,420 [salt.loaded.int.module.mine][ERROR   ][26745] Function freedisks.list in mine_functions no

We might consider to just remove cephdisks.list from the mine_functions.conf

**Comment by theanalyst** [comment]
I think we should move it out of source tree, ideally we'd have a docs folder (which we should probably do soon, ie. make the wiki into a doc and use that) or an eg. folder where we can keep these things and delete this

**Comment by jan--f** [comment]
> I think we should move it out of source tree

I agree. We still have it as part of the git history, should we need it.
