### ISSUE TITLE
"DeprecationWarning: This server_id is computed nor by Adler32 neither by CRC32" in salt-run output

### ISSUE THREAD

**Issue by tserong** [SUSE/DeepSea#1593]
#1530 appends "server_id_use_crc: adler32" to /etc/salt/minion, but we also need this appended to /etc/salt/master, otherwise salt-run output is polluted with "[WARNING ] /usr/lib/python3.6/site-packages/salt/grains/core.py:2802: DeprecationWarning: This server_id is computed nor by Adler32 neither by CRC32. Please use "server_id_use_crc" option and define algorithm youprefer (default "Adler32"). The server_id will be computed withAdler32 by default."

**Comment by jschmid1** [comment]
yep, noticed that aswell a couple of days ago.. I have this on my radar and will submit a fix soon

**Comment by suykerbuyk** [comment]
Here at Seagate, we are running into this problem as well.  How do we work around it?

**Comment by jschmid1** [comment]
@suykerbuyk 

try adding `server_id_use_crc: adler32`

to your minion configuration. i.e. `/etc/salt/minion.d/crc_method.conf` and restart the salt-minion/master process.

If you're using deepsea 0.9.x this should happen automatically.

**Comment by suykerbuyk** [comment]
That seems to have worked, thank you!

Note:  I was running this version of DeepSea before (needing) to apply the fix:
sadmin:/srv # rpm -qi deepsea                                                                                                                                                                                                                                                              
Name        : deepsea                                                                                                                                                                                                                                                                      
Version     : 0.9.23+git.0.6a24f24a0
Release     : 3.3.2
Architecture: noarch
Install Date: Fri 13 Sep 2019 05:23:54 PM MDT
Group       : System/Libraries
Size        : 847686
License     : GPL-3.0
Signature   : RSA/SHA256, Fri 09 Aug 2019 02:02:00 AM MDT, Key ID 70af9e8139db7c82
Source RPM  : deepsea-0.9.23+git.0.6a24f24a0-3.3.2.src.rpm
Build Date  : Fri 09 Aug 2019 02:00:55 AM MDT
Build Host  : sheep61
Relocations : (not relocatable)
Packager    : https://www.suse.com/
Vendor      : SUSE LLC <https://www.suse.com/>
URL         : https://github.com/suse/deepsea
Summary     : Salt solution for deploying and managing Ceph
Description :
A collection of Salt files providing a deployment of Ceph as a series of stages.
Distribution: SUSE Linux Enterprise 15

**Comment by jschmid1** [comment]
glad to help
