### ISSUE TITLE
Enhance handling of 'Unknown host'

### ISSUE THREAD

**Issue by jschmid1** [SUSE/DeepSea#1623]
### Description of Issue/Question

Bug: https://bugzilla.suse.com/show_bug.cgi?id=1132271 

~This gives a stacktrace due to ' [ERROR   ] Exception during resolving address: [Errno 1] Unknown host'.~

In disks.py:207

``` python
def destroyed():
    """ List destroyed (about to be replaced) disks
    """
    # This can't be solved with Popen since the salt-master is running as salt:salt
    local_client = salt.client.LocalClient()
    ret: str = local_client.cmd(
        "roles:master",  # <--- If this is not assigned, we get {} back
        'cmd.shell', ['ceph osd tree destroyed --format json'],
        tgt_type='pillar')

    ret = list(ret.values())[0]     <-- improve this
    tree = json.loads(ret).get('nodes')
```

This runs into an IndexError when there is a bad return.

edit: This happens due to an unassigned master role

**Comment by jan--f** [comment]
Yep saw this too. Happens when the disks runner is ran before roles are assigned. I have a fix in the pipe.

**Comment by jschmid1** [comment]
was about to write that :dagger:

**Comment by jschmid1** [comment]
On 19/04/24 04:08, Joshua Schmid wrote:
> was about to write that :dagger: 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/SUSE/DeepSea/issues/1623#issuecomment-486178252

Corrected the issue.

-- 
Joshua Schmid
Software Engineer
SUSE Enterprise Storage
