### ISSUE TITLE
stage.0 should enable salt-minion

### ISSUE THREAD

**Issue by abonillasuse** [SUSE/DeepSea#182]
If the salt minion is not running on the admin, it may cause several problems down the road. Stage 0 should systemctl enable salt-minion on all nodes.

**Comment by abonillasuse** [comment]
@mvechava

**Comment by tserong** [comment]
The minion would already need to be running in order for stage 0 to be able to do that, wouldn't it?

**Comment by abonillasuse** [comment]
@tserong the minion would be running, not necessarily enabled on boot. Which stage.0 should sanity check for.

**Comment by swiftgist** [comment]
We think this might drive an admin mad when then intentionally disable a Salt minion and DeepSea keeps enabling it.
