### ISSUE TITLE
DeepSea doesn't know how to deploy ceph-mgr

### ISSUE THREAD

**Issue by tserong** [SUSE/DeepSea#183]
Since Kraken, ceph-mgr will be automatically started on the mon nodes if it's not otherwise configured to run elsewhere. We should teach DeepSea how to deploy ceph-mgr for the case where you don't want to run it on the mon nodes (the service will need to be masked on the mon nodes and enabled and started on whatever other nodes the user chooses).

**Comment by LenzGr** [comment]
Good suggestion - I wonder if that would become another possible node role?

**Comment by swiftgist** [comment]
I think that would make the most sense.  Volker is doing something similar for an openattic role.  https://github.com/votdev/DeepSea/commit/7557af6d7535b673ad5b536b0db2e1d3d0cecfcb

Same idea, but for ceph-mgr.

**Comment by tserong** [comment]
Note to self: also add an mgr section for custom config (see #256)

**Comment by tserong** [comment]
The client admin keyring will also need `caps mgr  = "allow *"`

**Comment by tserong** [comment]
Working on this now (the systemd magic to automatically create mgrs is going away soon -- see https://github.com/ceph/ceph/pull/16023)

**Comment by tserong** [comment]
Don't close this yet. Once #398 is merged, we still need to add:

- remove
- rescind
- mgr support when importing existing clusters
- mgr section for custom config as mentioned above

(`caps mgr = "allow *" has already been taken care of)
