### ISSUE TITLE
Keep track of which stages have been run

### ISSUE THREAD

**Issue by smithfarm** [SUSE/DeepSea#184]
We already had an issue that was (apparently) caused by someone neglecting to run DeepSea stage 3 when deploying a cluster.

Is there a straightforward way of determining which DeepSea stages have been run? (And, if there was, would it be reasonable to include that in the supportconfig plugin?)

**Comment by swiftgist** [comment]
Straightforward?  Probably not, other than the first run on a fresh deployment.  I think this may go with the "Add more/better validation steps" for other stages.

**Comment by smithfarm** [comment]
> Probably not, other than the first run on a fresh deployment.

I'm not suggesting anything more than this. Every deployment will be "fresh" at the beginning. So simply keep track of which stages from {0,1,2,3} have been run. 

Then, in the supportconfig for the Salt Master we can have a little DeepSea sanity check that could look like this:

```
DeepSea deployment sanity:
Stage 0: YES
Stage 1: YES
Stage 2: YES
Stage 3: NO
```

It would not give any positive assurance that the deployment is without glitches, of course, but if someone did not run one or more stages for any reason, that would be immediately apparent to us. (And, more importantly, to L2/3 before it gets to us.)

**Comment by swiftgist** [comment]
We believe the events/stages should be appearing in the logs.  If not, please reopen.
