### ISSUE TITLE
Opt-in option to update kernel in stage

### ISSUE THREAD

**Issue by BlaineEXE** [SUSE/DeepSea#186]
I think the user should be able to specify somewhere explicitly that they do or don't want to update their kernel. Some users may standardize on a particular kernel or even have a custom kernel they want to run on their servers. If we update the kernel out from under these users without telling them, I can see someone being very upset. I conjecture that a worst-possible case might even be that this could put them at risk of legal non-compliance if the kernel they have standardized on is for compliance reasons.

**Comment by rjfd** [comment]
@BlaineEXE check the discussion in #60

**Comment by BlaineEXE** [comment]
Roger, @rjfd. Closing this.
