### ISSUE TITLE
rescind of storage role: should we wipe any ceph drives?

### ISSUE THREAD

**Issue by jan--f** [SUSE/DeepSea#191]
Wondering if we should actually wipe any drives found to be formatted for ceph on a no-longer-storage node.
Right now we only wipe drives that are mounted at the time rescind is called on a storage node.

**Comment by jan--f** [comment]
We could alternatively use ```ceph-disk list``` to wipe drives.

**Comment by swiftgist** [comment]
@jan--f Are you seeing the issue if the unmount works but the rest somehow does not, we leave the admin in a bad spot after running a ceph.purge?

Were you looking at https://github.com/SUSE/DeepSea/blob/master/srv/salt/ceph/rescind/storage/default.sls#L36 to become a smaller loop just for the unmounting and then invoking cephdisks.list locally for a second loop?  

The hard coded partitions will be a problem with the addition of bluestore/dmcrypt.  IIRC, the reason I did not rely on ceph-disk is that the zap operation is bundled with the OSD removal which requires an admin keyring.

The only other thing to consider is that cephdisks.list may change to include Ceph disks (i.e. contains a non-matching fsid).  That sounds fine and seems impossible to still have a Ceph disk from a previous installation not included in this cluster, but it might cause trouble.

**Comment by jan--f** [comment]
should be fixed.
