### ISSUE TITLE
Validate fails to account for master_minion/admin on multiple domains

### ISSUE THREAD

**Issue by BlaineEXE** [SUSE/DeepSea#208]
In my test cluster, (using vagrant-ceph) DeepSea reports the following error, even though the node configured as the master_minion is actually given the admin role.

```
master_role              : ['The master_minion does not match any minion assigned the master role']
```

I have tracked the bug to the following location in the code; 

```py
# In my case
# node = 'admin.ceph'
# master_minion = 'admin-public'
# Found at approximately line 422
if 'master_minion' in self.data[node] and node == self.data[node]['master_minion']:
    matched = True
```

When DeepSea is installed via RPM, `hostname -f` returns `admin-public`, so the `master_minion` pillar item is automatically given this name. When `populate` runs and generates configs, it detects the admin node by its alias `admin.ceph`. These hostnames are functionally equivalent, and I would even go further to consider `admin-public` to be preferable, as it is more specific as to which network is the intended management network.

By my reasoning, this test should test that the short hostnames are the same, not that the FQDNs (of which a node may have several) are the same.

**Comment by BlaineEXE** [comment]
I have found a similar case with mon validation.

```
salt-run state.orch ceph.stage.3     
firewall                 : disabled
fsid                     : valid
public_network           : valid
cluster_network          : valid
cluster_interface        : valid
monitors                 : valid
storage                  : valid
ganesha                  : valid
master_role              : valid
mon_host                 : valid
mon_initial_members      : valid
time_service             : valid
fqdn                     : ['fqdn mon2.ceph does not match minion id mon2', 'fqdn mon3.ceph does not match minion id mon3', 'fqdn data4.ceph does not match minion id data4']
[ERROR   ] No highstate or sls specified, no execution made
admin.ceph_master:
----------
          ID: validate failed
    Function: salt.state
        Name: just.exit
      Result: False
     Comment: No highstate or sls specified, no execution made
     Started: 13:55:24.511357
    Duration: 0.665 ms
     Changes:   

Summary for admin.ceph_master
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.665 ms
```

For testing, I printed out the `minion_id`s DeepSea is seeing:
``` 
['data3.ceph', 'admin.ceph', 'mon1.ceph', 'mon2', 'mon3', 'data4', 'data1.ceph', 'data2.ceph']
```

My /etc/hosts file:
```
cat /etc/hosts
#
# hosts         This file describes a number of hostname-to-address
#               mappings for the TCP/IP subsystem.  It is mostly
#               used at boot time, when no name servers are running.
#               On small systems, this file can be used instead of a
#               "named" name server.
# Syntax:
#    
# IP-Address  Full-Qualified-Hostname  Short-Hostname
#

127.0.0.1       localhost

# special IPv6 addresses
::1             localhost ipv6-localhost ipv6-loopback

fe00::0         ipv6-localnet

ff00::0         ipv6-mcastprefix
ff02::1         ipv6-allnodes
ff02::2         ipv6-allrouters
ff02::3         ipv6-allhosts

192.168.10.254  admin-management admin.ceph salt
192.168.10.11   mon1-management mon1.ceph
192.168.10.12   mon2-management mon2.ceph
192.168.10.13   mon3-management mon3.ceph
192.168.10.21   data1-management data1.ceph
192.168.10.22   data2-management data2.ceph
192.168.10.23   data3-management data3.ceph
192.168.10.24   data4-management data4.ceph

172.16.1.254    admin-public admin admin.ceph salt
172.16.1.11     mon1-public mon1 mon1.ceph
172.16.1.12     mon2-public mon2 mon2.ceph
172.16.1.13     mon3-public mon3 mon3.ceph
172.16.1.21     data1-public data1 data1.ceph
172.16.1.22     data2-public data2 data2.ceph
172.16.1.23     data3-public data3 data3.ceph
172.16.1.24     data4-public data4 data4.ceph

172.16.2.254    admin-cluster admin.ceph salt
172.16.2.11     mon1-cluster mon1.ceph
172.16.2.12     mon2-cluster mon2.ceph
172.16.2.13     mon3-cluster mon3.ceph
172.16.2.21     data1-cluster data1.ceph
172.16.2.22     data2-cluster data2.ceph
172.16.2.23     data3-cluster data3.ceph
172.16.2.24     data4-cluster data4.ceph
```

The method in question is:
```py
def fqdn(self):
        """
        Verify that fqdn matches minion id
        """
        for minion_id in self.grains.keys():
            fqdn = self.grains[minion_id]['fqdn']
            if fqdn != minion_id:
                msg = "fqdn {} does not match minion id {}".format(fqdn, minion_id)
                if fqdn != "localhost":
                    self.errors.setdefault('fqdn', []).append(msg)
                else:
                    self.warnings.setdefault('fqdn', []).append(msg)

        self._set_pass_status('fqdn')
```

It looks like DeepSea is grabbing a mix of public and non-public interfaces wherever it gets its `minion_id`s. Like the comment above, I feel like this check should be for the short hostname only.

It also makes me question whether DeepSea is limiting all of its network traffic to the management network. It could degrade Ceph performance if DeepSea is using any/all networks including cluster nets for management traffic.

**Comment by swiftgist** [comment]
what does "salt-key -L" show?  Are your minion ids fully qualified?

**Comment by BlaineEXE** [comment]
```
> salt-key -L
Accepted Keys:
admin.ceph
data1.ceph
data2.ceph
data3.ceph
data4
mon1.ceph
mon2
mon3
Denied Keys:
Unaccepted Keys:
Rejected Keys:
```

**Comment by swiftgist** [comment]
We are enforcing that hostname and minion id match.  Using salt commands with regular host resolution commands resulted in confusion with several people.  We also realized that users could put themselves in situations where host data1 is minion id data2 and host data2 is minion id data1.  (I know it seems unlikely, but the point of the validation is a sanity check that the admin is consistently referring to a node.)

**Comment by BlaineEXE** [comment]
__Regarding my first original comment:__

As for enforcing strict hostname and minion id match, I can understand that argument. Perhaps a note as such should be placed in `master_minion.sls`? Currently all I see in the Readme.md is `Edit /srv/pillar/ceph/master_minion.sls` without mention of what a suitable value should be. This needs updated.

I'd also like to talk about removing the line `sed -i '/^master_minion:/s!_REPLACE_ME_!'`hostname -f`'!' /srv/pillar/ceph/master_minion.sls` from the makefile and specfile since it isn't generating a good default value and additionally adding a validation in stage 1 that errors out if the `_REPLACE_ME_` text is found in `master_minion.sls` with instructions as to what to do. This at least will notify the user they need to fix this earlier than stage 3, where I'm currently seeing the error message. If the value they choose is wrong, stage 3 will still give them an error.

__Regarding my second original comment:__

I can confirm that adding `interface: 192.168.10.254` (the IP address of the admin node's management interface) makes salt behave as appropriate. We should add this to the documentation under `Prepare Salt`.

```
> salt-key -L
Accepted Keys:
admin.ceph
data1.ceph
data2.ceph
data3.ceph
data4.ceph
mon1.ceph
mon2.ceph
mon3.ceph
Denied Keys:
Unaccepted Keys:
Rejected Keys:
```

**Comment by swiftgist** [comment]
If this is still an issue with 0.7, please reopen.
