### ISSUE TITLE
validate master is defined

### ISSUE THREAD

**Issue by swiftgist** [SUSE/DeepSea#227]
The validation needs to fail if no master has been defined in policy.cfg.

**Comment by BlaineEXE** [comment]
I was looking into this. Is this not basically checked already by `Validate.master_role()`?

**Comment by swiftgist** [comment]
I think it needs to move from the pillar function to the setup function.  Stage 0 relies on a master defined and fails miserably.

**Comment by swiftgist** [comment]
Strike that.  Let me go find the email on why I created this issue.

**Comment by swiftgist** [comment]
Validation failure on lacking a master role is fine.
