### ISSUE TITLE
switch from cmd.run to cmd.shell 

### ISSUE THREAD

**Issue by jschmid1** [SUSE/DeepSea#235]
/usr/lib/python2.7/site-packages/salt/utils/templates.py:73:
DeprecationWarning: Starting in 2015.5, cmd.run uses python_shell=False by
default, which doesn't suppor
t shellisms (pipes, env variables, etc). cmd.run is currently aliased to
cmd.shell to prevent breakage. Please switch to cmd.shell or set
python_shell=True to avoid breakage in the future, when this aliasing is
removed.

**Comment by BlaineEXE** [comment]
Can the fix for this be as simple as doing a global find-replace on `cmd.run` with `cmd.shell`?

**Comment by jschmid1** [comment]
With some additional testing - yes. I'd say so.

**Comment by jschmid1** [comment]
only touching .py files, as .sls files use still the old syntax (yay :-1: )
