### ISSUE TITLE
Should we s/ceph.cherrypy/ceph.salt-api/ ?

### ISSUE THREAD

**Issue by tserong** [SUSE/DeepSea#239]
I'm having a Tim-is-an-annoying-pedant moment. Why is ceph.cherrypy named ceph.cherrypy, rather than ceph.salt-api? I mean, it's there to install salt-api, which just happens to be using cherrypy internally...

**Comment by rjfd** [comment]
@tserong I totally agree with your observation. Please open a PR to change that.
