### ISSUE TITLE
Deploy and configure Prometheus node exporters on every node

### ISSUE THREAD

**Issue by LenzGr** [SUSE/DeepSea#243]
It would be nice if DeepSea would allow me to set up a functional monitoring infrastructure, by setting up a central monitoring node running [Prometheus](https://prometheus.io/) (and [Grafana](http://grafana.org/)?) and then deploy and configure the Prometheus [node_exporter](https://github.com/prometheus/node_exporter) on every Ceph cluster node, to gather some basic system statistics.

There's already a Salt Formula related to Prometheus - [saltstack-prometheus-formula](https://github.com/bechtoldt/saltstack-prometheus-formula) - maybe it can be used here?

**Comment by tserong** [comment]
I had a quick look at that salt formula, and most of it seems to be extracting prometheus binaries from tarballs and creating systemd unit files...

**Comment by swiftgist** [comment]
On Tuesday, May 09, 2017 03:19:13 AM Tim Serong wrote:
> I had a quick look at that salt formula, and most of it seems to be
> extracting prometheus binaries from tarballs and creating systemd unit
> files...

I haven't looked at your packages, but I would guess that extracting unit files 
isn't really needed.

**Comment by tserong** [comment]
> I haven't looked at your packages, but I would guess that extracting unit files isn't really needed.

Yeah, I reckon not. My latest golang-github-prometheus-prometheus, golang-github-prometheus-node_exporter and golang-github-digitalocean-ceph_exporter and grafana RPMs can all be found in https://build.opensuse.org/project/show/home:tserong for the moment if anyone wants to play.

**Comment by jan--f** [comment]
For now we will use the ceph_node_exporter. This doesn't need to be installed on all nodes afaik. It runs as a client to ceph (and needs a keyring) so any node will suffice.
Any opposition to simply putting it on the salt master? This node has an admin keyring anyway and I can't think of a reason against it of the top of my head.

**Comment by LenzGr** [comment]
@jan--f no objections against running the ceph_node_exporter on the Salt master by default. Yes, the regular node exporter needs to be installed on every node :)

**Comment by swiftgist** [comment]
PR Merged for exporters
