### ISSUE TITLE
Default targeting

### ISSUE THREAD

**Issue by swiftgist** [SUSE/DeepSea#245]
Capturing this here, since I do not see an existing issue.  Related bug in other systems concerning DeepSea using a subset of the Salt minions.  The summary is

1) DeepSea cannot use '*' as a default in Stages... too dangerous for any combined deployments
2) Two different solutions
  a) Custom grain
  b) Custom search

3) Have Stage 0 validate fail until one is selected.  Allow admin to choose their preference.

As far as work to do, the ceph_tgt exists in https://github.com/SUSE/DeepSea/tree/eric-integration.  The sls for creating a custom grain, poking the minion needs to be written.  Change all stages and rolling upgrade to use look for ceph_tgt and default to deepsea grain.  If neither is set and the validation is skipped, no minions are selected.

**Comment by jan--f** [comment]
addressed in #526
