### ISSUE TITLE
DeepSea releases should be tagged in the git repository

### ISSUE THREAD

**Issue by LenzGr** [SUSE/DeepSea#254]
It would be helpful if official releases made from the git repo would be tagged accordingly. This makes it easier to quickly switch to a given version for testing.

**Comment by jan--f** [comment]
agreed. I'll start doing this if @swiftgist has no objections?

**Comment by theanalyst** [comment]
@jan--f we could gpg-sign the new release tags as well here

**Comment by jan--f** [comment]
@theanalyst do we gain anything considering that we don't sign any commits?

**Comment by theanalyst** [comment]
@jan--f we could have some sort validation in package builds and such, cc @ddiss

**Comment by jan--f** [comment]
I pushed a few tags now and will continue to do so in the future. I did not tag releases prior to 0.7.5, if you need me to, let me know.

I will close this issue, lets open another one for the tag signing if desirable.
