### ISSUE TITLE
Check if apparmor is running

### ISSUE THREAD

**Issue by abonillasuse** [SUSE/DeepSea#263]
Whike on stage.3
mgt1:~ # salt-run state.orch ceph.stage.3
fsid                     : valid
public_network           : valid
public_interface         : valid
cluster_network          : valid
cluster_interface        : valid
monitors                 : valid
storage                  : valid
master_role              : valid
mon_host                 : valid
mon_initial_members      : valid
time_server              : valid
fqdn                     : valid
**APPARMOR** : valid

Ensure Apparmor is -not- running.

**Comment by ddiss** [comment]
I agree that it would make sense to check whether Apparmor is running. However, it shouldn't necessarily be considered an error - a user may have configured an appropriate Apparmor profile for OSDs, mons, etc.

**Comment by swiftgist** [comment]
I think this would go next to the firewall check at Stage 0, which is also a warning.  In time, the firewall check will become smarter (i.e. check ports).  Maybe we could do the same with apparmor and verify that DeepSea and Ceph are allowed to write to various parts of /var/lib/ceph.

**Comment by smithfarm** [comment]
The question is: "disable by default and allow user to explicitly enable, or enable by default and allow user to explicitly disable?"

Before we answer that question, we should consider at least the following:

1. if AA is found to be running, how likely is it that a user will have configured AA properly?
2. if AA is found to be running, how likely is it that this is an oversight, given how easy it is to enable AA when installing SLE?

**Comment by abonillasuse** [comment]
Today, osd deployment fails with AA on. Unless we ship a policy, it is a blocker to have AA running.

**Comment by swiftgist** [comment]
Added #273.  Only a warning check.

**Comment by abonillasuse** [comment]
Looks good @swiftgist - Close this one?

**Comment by smithfarm** [comment]
Note that if you add a line saying `Fixes: https://github.com/SUSE/DeepSea/issues/263` to a commit or PR description, the issue will get closed automatically when the PR is merged.
