### ISSUE TITLE
rescind/remove/purge should also remove stale systemd-service files

### ISSUE THREAD

**Issue by jschmid1** [SUSE/DeepSea#296]
currently we do:
  * de-auth
  * stop service
  * ensure an absent keyring

remnants in the form of service files should be removed

**Comment by swiftgist** [comment]
I think we need to disable the service.  I have this is the OSDRemove of osd.py.  I think that covers everything.

**Comment by jschmid1** [comment]
> I think we need to disable the service. I have this is the OSDRemove of osd.py. I think that covers everything.

That's the case. See
https://github.com/SUSE/DeepSea/blob/master/srv/salt/_modules/osd.py#L1174
