### ISSUE TITLE
 Failed to detect PackageManager on Tumbleweed

### ISSUE THREAD

**Issue by denisok** [SUSE/DeepSea#309]
>ID: packagemanager update regular                                                             
Function: module.run                                                                                
Name: packagemanager.up                                                                         
Result: False                                                                                     
Comment: Module function packagemanager.up threw an exception. Exception: Failed to detect PackageManager for OS.Open an issue on github.com/SUSE/DeepSea

`self.platform = linux_distribution()[0].lower()` in `/srv/salt/_modules/packagemanager.py` doesn't work for Tumbleweed as `/etc/SuSE-release` doesn't exists.

According to [bpo-1322](https://bugs.python.org/issue1322) pip [ld](https://pypi.python.org/pypi/ld) package should be used instead. That works.

> platform.linux_distribution Deprecated since version 3.5, will be removed in version 3.7.

So seems according to Python community that wouldn't be fixed.

What we should do ? I am not sure we could pip for SLES, or maintain [patch](https://bugs.python.org/issue17762) downstream.

As workaround just create file `echo "salt '*' cmd.run 'echo "openSUSE 20170605 (x86_64)" >> /etc/SuSE-release' `

**Comment by jschmid1** [comment]
uch, yes. I knew this will give us a headache in the future.

The correct way is to use /etc/os-release which was adopted by the major distributions over the last years. See [https://www.freedesktop.org/software/systemd/man/os-release.html](url) 

The OS detection has to be handled differently in future releases. 
Putting that on my plate.

**Comment by denisok** [comment]
yeah, as I understood reading the bug, they want to separate OS distr/version detection from standard lib.

It is also probably not that reliable to implement our own based in systemd standard.

Maybe good way to go is to use `pip ld`. Trying to install it without exception and import both if that was successful.

```
from platform import linux_distribution
try: from ld import linux_distribution
except ImportError: pass
```

but we need to find out if we want that dependency with pip. Probably logic behind that is not straightforward either (python2-pip, python3-pip ... pip, pip2, pip2.7, pip3, pip3.5). Somehow on my Tumbleweed python resolves to 2.7 but pip for 3.5 :-)

>lrwxrwxrwx 1 root root     9 May 22 11:04 /usr/bin/python -> python2.7
>lrwxrwxrwx 1 root root  21 Apr 19 19:05 /usr/bin/pip -> /etc/alternatives/pip
-rwxr-xr-x 1 root root 364 Apr 19 19:05 /usr/bin/pip2
-rwxr-xr-x 1 root root 368 Apr 19 19:05 /usr/bin/pip2.7
-rwxr-xr-x 1 root root 364 Nov 13  2016 /usr/bin/pip3
-rwxr-xr-x 1 root root 368 Nov 13  2016 /usr/bin/pip3.5
lrwxrwxrwx 1 root root 15 Jun 29  2016 /etc/alternatives/pip -> /usr/bin/pip3.5

**Comment by jan--f** [comment]
@denisok Where did you encounter this? This is a salt issue, not deepsea. The package manager interface is unfortunately broken for all but the most basic usage patterns.

In DeepSea we usually work around it by using ```cmd.run 'zypper ...'```. This breaks other distros, but even that could be worked around.
I'd prefer to avoid a dependency on pip.

**Comment by denisok** [comment]
@jan--f using DeepSea on Tumbleweed to deploy the cluster. ld is used in DeepSea: /srv/salt/_modules/packagemanager.py

**Comment by jan--f** [comment]
ah indeed...thx @denisok I didn't know that. I'll look at this to change it to parse /etc/os_release.

**Comment by swiftgist** [comment]
I wonder if we shouldn't be using 'osfinger' or similar here.  Or is this something that should be SUSE specific and the sls that invokes packagemanager.py should be under a SUSE subdirectory?

**Comment by jschmid1** [comment]
I changed ` linux_distribution()[0].lower()` to `__grains__['os'].lower()`

should work fine with tumbleweed now.

Closing -> Please re-open if issue persists.
