### ISSUE TITLE
nettest only tests IPv4

### ISSUE THREAD

**Issue by l-mb** [SUSE/DeepSea#31]
Customers may be using IPv6.

 address_list = local_client.cmd(node, 'grains.get', ['ipv4'])

At the very least, nettest needs to detect if IPv6 addresses are used and abort with an appropriate error message.

**Comment by oms4suse** [comment]
We will need another runner for gathering ipv6 commands.

This should not be hard but I don't yet have ipv6 in my test rigs.

**Comment by swiftgist** [comment]
I would like to collapse this into IPv6 support in general for DeepSea.  AFAIK, the demand seems low currently.

**Comment by jan--f** [comment]
Closing since nettest componentis currently being re-written.
