### ISSUE TITLE
Stage 3 hangs on invalid policy.cfg

### ISSUE THREAD

**Issue by smithfarm** [SUSE/DeepSea#323]
While developing the DeepSea suite I have repeatedly encountered a hang in Stage 3 when policy.cfg is not sane.

**Comment by swiftgist** [comment]
What is the validation not catching?  Or do you have DEV_ENV enabled?

**Comment by smithfarm** [comment]
DEV_ENV is enabled, yes. Does that disable *all* policy.cfg validation?

**Comment by swiftgist** [comment]
No, but some that prevent these problems are.
