### ISSUE TITLE
Warn user to configure networks

### ISSUE THREAD

**Issue by abonillasuse** [SUSE/DeepSea#329]
Is is quite easy to forget to look at certain files or even rush to stage.2 and suddenly have to change many files manually because deepsea used the wrong network order.

Please warn the user to look at
proposals/role-mon/stack/default/ceph/minions/ for the correct public network IP
and
proposals/config/stack/default/ceph/cluster.yml for the correct networks

I don't know if by just editing proposals/config/stack/default/ceph/cluster.yml after stage.1 is enough, but it should be made clear that verifying that file is important before proceeding!

**Comment by swiftgist** [comment]
Added with #585.  During Stage 2, the networks will be printed as a reminder of their current values.
