### ISSUE TITLE
Provide details on how to avoid ipv6 errors

### ISSUE THREAD

**Issue by abonillasuse** [SUSE/DeepSea#336]
[WARNING ] Unable to find IPv6 record for "ip-172-30-2-221.ec2.internal" causing a 10 second timeout when rendering grains. Set the dns or /etc/hosts for IPv6 to clear this.

Are all over, and 99% of those using SES will not use IPv6. Can we not use it by default?

**Comment by swiftgist** [comment]
This message looks to be fixed in Salt itself in 2016.11.6.  See https://github.com/saltstack/salt/issues/40912

At the moment, DeepSea is only handling IPv4 addresses in calculating/converting any addresses.  The comments are in populate.py with IPv6 on the TODO list.
