### ISSUE TITLE
Change stage.0 messages "starting host"

### ISSUE THREAD

**Issue by abonillasuse** [SUSE/DeepSea#337]
The message of
"[WARNING ] Starting host ip-172-30-2-23.ec2.internal"
is confusing and not clear on what it is exactly starting, it makes one thing it's being rebooted.

**Comment by swiftgist** [comment]
Would you rather have "Starting on host"?  We put the message there so that you could see progress when minions were processed sequentially.

**Comment by abonillasuse** [comment]
How about

'Processing Host...'?

On Jun 15, 2017 4:02 PM, Eric Jackson <notifications@github.com> wrote:

Would you rather have "Starting on host"? We put the message there so that you could see progress when minions were processed sequentially.
