### ISSUE TITLE
restart and shared names

### ISSUE THREAD

**Issue by swiftgist** [SUSE/DeepSea#34]
I added shared keyrings a while back.  The consequence of this is that the service names are simpler and different if the admin configures this.  The restart needs to handle those cases as well.  

The two cases are mds and rgw.  Compare the default.sls to the shared.sls in each directory.

**Comment by jan--f** [comment]
Is this still an issue? Keyrings have been refactored since, haven't they?

**Comment by jschmid1** [comment]
I see, the difference is basically:

ceph-mds@{{ grains['host'] }}

vs.

ceph-mds@mds

this extends to: rgw
