### ISSUE TITLE
sequential reboot

### ISSUE THREAD

**Issue by swiftgist** [SUSE/DeepSea#35]
In stage/prep/minion/default.sls, there is a restart call to ceph.updates.restart.  

Since this is a minion file targeted from orchestration, these will run in parallel.  Now, the reboot only happens when there's a kernel update.  During a fresh installation, a parallel update/reboot is desirable.

Once a cluster is running, a sequential reboot is necessary.  The preference is to keep all other steps running in parallel and only run the reboots sequentially when something like roles are defined.

My first guess would be create a salt-runner that returns each minion name in the proper order according to role or return '*' and hope that will work as a target.  The "proper" order should reflect the same order as the restart orchestration (i.e. ceph/restart/default.sls)

**Comment by jschmid1** [comment]
this is addressed by pullrequest #43
