### ISSUE TITLE
NFS-Ganesha RGW: check in ganesha.conf.j2 if bucket creation succeded. 

### ISSUE THREAD

**Issue by supriti** [SUSE/DeepSea#397]
In ganesha.conf.j2 (https://github.com/SUSE/DeepSea/blob/master/srv/salt/ceph/ganesha/files/ganesha.conf.j2) we are adding "Path = "{{ user }}-demo";" But it may happen that for some reason bucket creation failed. Deploying ganesha with non existent bucket will result in nfs-ganesha failure:

"init_export_root :EXPORT :CRIT :Lookup failed on path, ExportId=2 Path=demo-demo FSAL_ERROR=(No such file or directory,2)"

We should add a check that bucket is actually present.

**Comment by swiftgist** [comment]
Fixed in #682
