### ISSUE TITLE
verify the healthiness of roles

### ISSUE THREAD

**Issue by jschmid1** [SUSE/DeepSea#42]
Currently we monitor the clusters health based on the information `ceph health` gives you.
That is alright to a certain extend - We might have wrong information if we reboot monitors in a setup > 3 and something goes wrong. `ceph health` will tell you that you might have lost a monitor and drop to `HEALTH_WARN`. So we happily go along an restart the next one ( the exit condition is `HEALTH_ERR` for reason [0] ). The issue here is that you only notice if something went wrong when you lost the critical amount of monitors already. So the goal here is to look for a better way to look for the status like systemdctl status etc.

[0] `HEALTH_WARN` is too vague to drop out with error. there are many non-critical cases where ceph gives you a warning.

**Comment by swiftgist** [comment]
Marking this complete with cephservices.py added.
