### ISSUE TITLE
Upgrading to 0.7.16 results in broken sharedsecret.conf

### ISSUE THREAD

**Issue by tserong** [SUSE/DeepSea#443]
DeepSea's specfile includes:

````
%post
if [ $1 -eq 1 ] ; then
  # Initialize to most likely value
  sed -i '/^master_minion:/s!_REPLACE_ME_!'`hostname -f`'!' /srv/pillar/ceph/master_minion.sls
  sed -i '/^sharedsecret: /s!{{ shared_secret }}!'`cat /proc/sys/kernel/random/uuid`'!' /etc/salt/master.d/sharedsecret.conf
  chown salt:salt /etc/salt/master.d/sharedsecret.conf
fi
````

So for initial install (the `$1 eq 1` case), /etc/salt/master.d/sharedsecret.conf will end up having a sensible random secret sedded into it.

When upgrading from an older version however, $1 will eq 2, so the sed doesn't happen, and every subsequent `salt` invocation will spit out "Error parsing configuration file: /etc/salt/master.d/sharedsecret.conf - while constructing a mapping in "<string>", line 1, column 15: sharedsecret: {{ shared_secret }}".

Can we move the sed and chown in %post to outside the conditional so they always happen? If there's already a suitable shared secret in place, that sed invocation should be a NOOP anyway, right?

**Comment by tserong** [comment]
Also, why is `install -m 600 srv/salt/ceph/salt-api/files/sharedsecret.conf.j2 $(DESTDIR)/etc/salt/master.d/sharedsecret.conf` in the install section of the Makefile, not the copy-files section? If it were moved to copy-files, then this wouldn't need to be duplicated in the %install section of the specfile.

**Comment by rjfd** [comment]
@tserong you're totally right. Will open a PR as soon as I can.

**Comment by tserong** [comment]
@rjfd thanks!
