### ISSUE TITLE
Import should automatically add master to policy.cfg

### ISSUE THREAD

**Issue by tserong** [SUSE/DeepSea#444]
policy.cfg generated by `salt-run populate.engulf_existing_cluster` gives you a policy.cfg that matches a running cluster... which doesn't include the master role. This means you have to manually add `cluster-ceph/cluster/HOSTNAME.sls` and `role/master/cluster/HOSTNAME.sls` lines to policy.cfg, else stage 3 will fail with "The master_minion does not match any minion assigned the master role".

We should probably make it automatically inject appropriate master lines into policy.cfg, unless anyone can think of a reason not to...?

**Comment by swiftgist** [comment]
I agree, those lines should be added.

**Comment by jan--f** [comment]
Sorry, didn't get to this today.

**Comment by tserong** [comment]
It's alright, I'm on it.

**Comment by tserong** [comment]
* *gah* *

Due to a small "wrong terminal window" accident, I've just pushed the fix for this to master, without anyone else having reviewed it (see https://github.com/SUSE/DeepSea/commit/d4f5d25).

I *did* test it though. @swiftgist, do you want me to revert master to HEAD~1 then go through a proper PR, or just run with it as is?

**Comment by jan--f** [comment]
@tserong no worries. I think its fine.

**Comment by tserong** [comment]
Thanks @jan--f
