### ISSUE TITLE
stage 4 after importing cluster with rgw fails (missing "rgw.configurations")

### ISSUE THREAD

**Issue by tserong** [SUSE/DeepSea#447]
On an imported cluster with rgw running on one node:

````
# salt-run  state.orch ceph.stage.4
[ERROR   ] Run failed on minions: ses4-5.example.com
Failures:
    ses4-5.example.com:
        Data failed to compile:
    ----------
        Rendering SLS 'base:ceph.rgw.keyring.default' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'rgw.configurations'
````

(I'll dig up more detail later, but wanted to record this now so it doesn't get forgotten)

**Comment by swiftgist** [comment]
Did ses4-5 not get all the modules?  I've had that happen under various circumstances (sometimes adding a new version of a module and not sync'ing or running "salt '*' saltutil.sync_modules" and not realizing that one node failed.)

The quick check is 

`salt '*' rgw.configurations`

The rgw roles will return something such as 'rgw' and the rest will return "".

**Comment by tserong** [comment]
Now it's happening to all my nodes except the master. Weirdly, I get:

````
ses4-0:~ # salt '*' rgw.configurations
ses4-0.example.com:
ses4-4.example.com:
    'rgw.configurations' is not available.
ses4-5.example.com:
    'rgw.configurations' is not available.
ses4-3.example.com:
    'rgw.configurations' is not available.
ses4-2.example.com:
    'rgw.configurations' is not available.
ses4-1.example.com:
    'rgw.configurations' is not available.
ERROR: Minions returned with non-zero exit code
````

No amount of `salt '*' saltutil.sync_modules` seems to help.

I'll return to this tomorrow with a fresh set of eyes...

**Comment by tserong** [comment]
Found it, after turning on debug logging on the other minions:

````
2017-07-13 13:37:24,709 [salt.loader      ][DEBUG   ][12320] Failed to import module rgw:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1333, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/var/cache/salt/minion/extmods/modules/rgw.py", line 8, in <module>
    import boto
ImportError: No module named boto
````

4c128c3 added a dependency on python-boto, which I didn't have installed, because I hadn't re-run stage 0 since I installed the latest DeepSea...

Does salt provide a way to make ImportError exceptions in modules on minions in any way remotely obvious?
