### ISSUE TITLE
Adjust the upgrade process if mon/osd colocated

### ISSUE THREAD

**Issue by jschmid1** [SUSE/DeepSea#449]
Apparently OSDs refuse to start if not _all_ MONs are >= luminous. 

The current approach `ceph.maintenance.upgrade` follows is to process each minion in the recommended order with a subsequent reboot.
That behavior is fine with dedicated services, but fails in a colocated-service-layout where OSDs are on the same host as MONs are(which is due to the current cluster sizes quite likely).

Instead of rebooting the node we have to switch to an indivial service based 'restart'

**Comment by swiftgist** [comment]
Could we switch to the service restart for only the monitors?  That would keep the rest of the behavior the same.

For dedicated nodes, the check at the end of the upgrade could include the monitors with the "remaining" nodes.  That should still prevent any lingering `zypper ps` processes.  Any shared roles would be caught during the other role update.
