### ISSUE TITLE
OSD data+journal partitions get created, but not mounted ("missing OSDs")

### ISSUE THREAD

**Issue by smithfarm** [SUSE/DeepSea#457]
Intermittently in DeepSea integration testing, we are seeing "missing OSDs" - i.e. after stage 3 the number of OSDs in the cluster is lower than expected.

For example, in this run: https://paste2.org/kcd1mIVC

Notice how there are two storage nodes, each with two OSD disks. All four disks are partitioned, but only the disks on target147135135005.teuthology are mounted. The ones on the other storage node are not mounted.

@jan--f @swiftgist @jschmid1

**Comment by jan--f** [comment]
Do we have access to the minion logs?

**Comment by smithfarm** [comment]
Yes, see http://147.135.133.225/ubuntu-2017-07-14_08:05:26-deepsea-ses5---basic-openstack/87/remote/

To make things a bit easier, this command will download them to your machine (into a directory called `remote`): `wget -r --no-parent -nH --cut-dirs=2 http://147.135.133.225/ubuntu-2017-07-14_08:05:26-deepsea-ses5---basic-openstack/87/remote/`

**Comment by smithfarm** [comment]
I have them on my laptop now in `~/scratch/logs-deepsea-457-1` if the above URL goes stale.

**Comment by smithfarm** [comment]
Tried with ceph milestone 9 candidate and latest DS master - no longer reproducible.
