### ISSUE TITLE
Automatically create RGW system user

### ISSUE THREAD

**Issue by rjfd** [SUSE/DeepSea#459]
In order to manage RGW using the RGW Admin Ops API, we need a user with "system" permissions.
Currently, if the sysadmin wants DeepSea to create an RGW user it requires to add the RGW configuration to the pillar manually.

What is happening is that in most cases the sysadmin forgets to add that information to the pillar and deploys RGW without creating any user. Then it creates this user manually using `radosgw-admin`, which will not be known by DeepSea.

Shouldn't we automatically create a "system" user upon RGW deployment?

**Comment by rjfd** [comment]
@theanalyst @swiftgist what do you think?

**Comment by rjfd** [comment]
Also, documentation should be improved. The only reference to configure RGW users in the NFS-Ganesha section.

**Comment by supriti** [comment]
Related to https://github.com/SUSE/DeepSea/issues/293 
For nfs-ganesha, its a requirement to have a user defined.

**Comment by swiftgist** [comment]
I always prefer defaults working... is the only negative that some admin may not like the username?  In that case, the admin would have to create the preferred system user and delete the default.  I think if we detect that at least one system user exists and we do not create the default, I think that's fine.

**Comment by abonillasuse** [comment]
I deployed with SES5-M10 today and the deployment of rgw does not implement an admin user. I had to do it by adding rgw.sls to /srv/salt/ceph/ and re-deploying. A system user is needed for openAttic too. Can we verify this task is performed with the rgw-role? Thanks!

**Comment by jecluis** [comment]
@abonillasuse this is an upstream project; SUSE-specific product questions should go through the proper channels. Alternatively, provide the deepsea version you are using and any other information that may be publicly relevant, but please refrain from mentioning product names, tags, and whatever else in public channels.

**Comment by swiftgist** [comment]
Fixed in #607
