### ISSUE TITLE
Jijna error with salt version 2016.3.4 

### ISSUE THREAD

**Issue by supriti** [SUSE/DeepSea#50]
This error is not seen with salt version salt 2015.8.10. With salt version 2016.3.4, running deepsea stage 3 gives the following error: 

admin.ceph_master:
    Data failed to compile:
----------
    Rendering SLS 'base:ceph.stage.3.default' failed: Jinja error: runner() got multiple values for keyword argument 'name'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 4, in top-level template code
TypeError: runner() got multiple values for keyword argument 'name'
 
; line 4
 
---
 
{% set FAIL_ON_WARNING = salt['pillar.get']('FAIL_ON_WARNING', 'True') %}
 
{% if salt['saltutil.runner']('ready.check', name='ceph', fail_on_warning=FAIL_ON_WARNING)  == False %}    <======================
ready check failed:
  salt.state:
    - name: "Fail on Warning is True"
    - tgt: {{ salt['pillar.get']('master_minion') }}
    - failhard: True
[...]
---
retcode:
    1

**Comment by jan--f** [comment]
doesn't happen with  2015.8.7 (Beryllium)

**Comment by rjfd** [comment]
I think the problem is that when salt calls a runner, in the new version, the parameter `name` is reserved for internal use. To fix this, we just need to rename the first parameter of the `ready.check` and `validate.pillar` functions.

I'll open a PR with a fix.
