### ISSUE TITLE
Create a rgw-ssl variant for DeepSea

### ISSUE THREAD

**Issue by theanalyst** [SUSE/DeepSea#501]
Have a rgw-ssl.sls that provides an example to deploy RGW with ssl termination

**Comment by smithfarm** [comment]
Needs a test case in `qa/suites/basic/` too.

**Comment by theanalyst** [comment]
@smithfarm agree

**Comment by theanalyst** [comment]
yes, I forgot to x-ref the issue when I created this, we have tests as well now
