### ISSUE TITLE
cephinspector always assumes filestore

### ISSUE THREAD

**Issue by tserong** [SUSE/DeepSea#522]
If I'm reading the code correctly, the cephinspector module always sets `ceph_disks["ceph"]["storage"]["osds"][partition]["format"] = "filestore"`, which presumably means it will generate incorrect profiles when run against a cluster with bluestore OSDs.

**Comment by kmroz** [comment]
@tserong - We did this intentionally.  The admin then runs the filestore to bluestore conversion @swiftgist wrote up.

@swiftgist/@tserong - Did we not think this through correctly?  Should engulf handle bluestore OSDs, given that ceph-deploy did not?  Perhaps it does now?

**Comment by smithfarm** [comment]
The engulf feature is only supposed to be used on SES4 clusters, right? There's no bluestore in SES4.

After the upgrade to SES5, the cluster will still be on filestore. Then the user can run the normal filestore-to-bluestore conversion orchestration if they want to.

**Comment by smithfarm** [comment]
The question, then, is "under what conditions (if any) would engulf be run on a SES5 cluster?"

If it's even possible to run it on SES5, then maybe we should consider eliminating that possibility?

**Comment by swiftgist** [comment]
I think we are at the crossroads of what the original requirements were for the engulf and what they could be.  The original set focused on importing a cluster created with ceph-deploy.  I can see a new set of requirements including any other installation (e.g. Ansible, DeepSea with a lost admin node, etc.) with all the supported components.

Considering how new Bluestore is, I don't think hardcoding the format to filestore is tragic at this point.

**Comment by tserong** [comment]
> The question, then, is "under what conditions (if any) would engulf be run on a SES5 cluster?"

Someone trying to recreate a trashed admin node.

> If it's even possible to run it on SES5, then maybe we should consider eliminating that possibility?

It runs just fine against SES5 - there's nothing in there that looks for any particular version of SES, it's just looking at all the cluster nodes, seeing what ceph pieces are present and generating a policy.cfg that matches what it finds.

**Comment by kmroz** [comment]
The admin node recovery is a good use case.

I'm thinking the check for bluestore vs filestore _should_ be as easy as checking the `fs_type` of a partition returned by `ceph-disk list`.

**Comment by tserong** [comment]
A (non-SES) use case: A ceph-deploy-deployed Luminous on openSUSE that wants migrating to DeepSea.

**Comment by smithfarm** [comment]
@tserong Thanks, that makes sense. Why throw away a perfectly good feature? ;-)
