### ISSUE TITLE
purge stops apache on admin node

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/DeepSea#528]
Had to realize that after a purge apache on the admin node did not run anymore / the purge stopped apache on the admin node.

A restart of apache is valid - but stopping it does interrupt other services (i.e. SMT / AutoYaST) hosted on the admin node and due to that the purge should not stop apache and leave it in stopped status.

**Comment by swiftgist** [comment]
#534 is waiting for review.

**Comment by swiftgist** [comment]
merged
