### ISSUE TITLE
rpm uninstall does not remove /srv/modules/../*.pyc

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/DeepSea#531]
when uninstalling the deepsea RPM the *.pyc files are left over:

/srv/modules/
/srv/modules/pillar
/srv/modules/pillar/stack.pyc
/srv/modules/runners
/srv/modules/runners/select.pyc
/srv/modules/runners/advise.pyc
/srv/modules/runners/benchmark.pyc
/srv/modules/runners/cephops.pyc
/srv/modules/runners/cephprocesses.pyc
/srv/modules/runners/configure.pyc
/srv/modules/runners/disengage.pyc
/srv/modules/runners/filequeue.pyc
/srv/modules/runners/minions.pyc
/srv/modules/runners/net.pyc
/srv/modules/runners/orderednodes.pyc
/srv/modules/runners/ready.pyc
/srv/modules/runners/proposal.pyc
/srv/modules/runners/push.pyc
/srv/modules/runners/remove.pyc
/srv/modules/runners/rescinded.pyc
/srv/modules/runners/sharedsecret.pyc
/srv/modules/runners/status.pyc
/srv/modules/runners/ui_ganesha.pyc
/srv/modules/runners/ui_iscsi.pyc
/srv/modules/runners/ui_rgw.pyc
/srv/modules/runners/upgrade.pyc
/srv/modules/runners/validate.pyc
/srv/modules/runners/populate.pyc

Can we somehow add these to the rpm uninstall process?

**Comment by smithfarm** [comment]
The RPM install process should compile the `.py` files and the deepsea package should own both the `.py` and the `.pyc` files. Then this won't happen.

**Comment by swiftgist** [comment]
I cannot recall the exact issue, but I thought we already ran into a problem when shipping pyc files.  This may have been related to the openATTIC rpm.

**Comment by smithfarm** [comment]
I peeked inside an arbitrary python module RPM (the one I looked at was `python-numpy`) and it contains both `.py` and `.pyc` files. The RPM *must* own the `.pyc` files; otherwise they will get left behind like Martin noted.

**Comment by smithfarm** [comment]
Python modules are typically packaged using `setuptools`. When you do `python setup.py build` the `.pyc` files get built. When you do `python setup.py install` they get installed. DeepSea needs to do something similar (and openATTIC, too, if it ships `.py` files).

**Comment by jan--f** [comment]
Afaik the byte code file are created when a module is first used. Wouldn't it be enough to simple add the respective ```pyc``` files to the spec file?

**Comment by smithfarm** [comment]
@jan--f I'm pretty (not 100%) sure you can't add non-existent files to the spec file. The RPM build process needs to create these artifacts - only then can they be packaged.

**Comment by smithfarm** [comment]
As I wrote above, for typical python modules that are packaged with setuptools, the `pyc` files are created as part of the build. DeepSea does not use setuptools, but it's trivial to compile a `.py` into a `.pyc` using `python -m py_compile`.
