### ISSUE TITLE
Ceph allows public and cluster networks to be specified as multiple subnets, DeepSea did too - but no longer (REGRESSION)

### ISSUE THREAD

**Issue by smithfarm** [SUSE/DeepSea#582]
In ceph.conf, `public_network` and `cluster_network` might be assumed to be a single subnet like 192.168.0.1/24, but Ceph actually allows multiple subnets as the value. See http://docs.ceph.com/docs/master/rados/configuration/network-config-ref/#id1 where it says: "You may specify comma-delimited subnets." `{ip-address}/{netmask} [, {ip-address}/{netmask}]`

DeepSea was handling the "multiple subnets" case nicely for some time, but some recent changes seem to have broken this. For details, see #580.

Here are two examples of code that breaks when `public_network` is either a string like "149.202.170.163/32, 149.202.170.164/32" or a list like `['149.202.170.163/32, 149.202.170.164/32']`:

https://github.com/SUSE/DeepSea/blob/f259476910ce5e5875a4f448a184e01860dc2d16/srv/modules/runners/populate.py#L933

https://github.com/SUSE/DeepSea/blob/e9ffafc41fe77f38557cafb9b2403e75677ae7f1/srv/salt/_modules/public.py#L40

Presumably there might be more.

**Comment by swiftgist** [comment]
I submitted #583 but I don't know why we are storing the multiple networks as a string in the pillar.  No other data structure does this IIRC.  I expected multiple networks to be an array originally.  For instance, look at roles for each of the minions.

In other words, when did the concatenated string in Salt become a requirement?

**Comment by smithfarm** [comment]
It would certainly make sense if Salt stored the subnets as an array. First, all the code that uses the subnets would be forced to take an array (even if it had just one element). Second, support for multiple subnets would be ensured.

**Comment by smithfarm** [comment]
As far as I can tell, the concatenated string was introduced by https://github.com/SUSE/DeepSea/pull/96 - @rjfd what do you think about changing this to an array?

**Comment by rjfd** [comment]
When I made that PR the only place where the public_network was used was to create the ceph.conf configuration using jinja, and therefore it was easier to use a string.

Now that the public_network is used elsewhere I also think it should be an array. People just need to make sure that update all places where this info is used.
