### ISSUE TITLE
stage.0: restart master_minion when running stage on master

### ISSUE THREAD

**Issue by rjfd** [SUSE/DeepSea#6]
There is a problem when executing this step https://github.com/SUSE/DeepSea/blob/master/srv/salt/ceph/stage/prep.sls#L34 if running the stage from the master node.

Don't know what should be the correct solution to this problem.
Should we assume that the `master_minion` is different from the salt-master node?

**Comment by swiftgist** [comment]
The master_minion is the salt master node, but the name of the salt master might not be the minion name.  For me, 

`salt 'admin.ceph' grains.get master`

returns salt.  If the master_minion does not match the actual minion name of the master, then salt will complain about no target matching.  That's why I added master_minion.sls since there's several reasons that the names might not match.

**Comment by rjfd** [comment]
@swiftgist right, but that was not my point.
The problem that I faced was: I was running an ssh session to the salt master node, and ran stage.0, which at some point tries to restart the salt master node, and kills my ssh session along with the salt-runner execution.

**Comment by swiftgist** [comment]
oh... sorry, working as intended.  Your master updated its kernel and needs to reboot.  As far as restarting the stage, that requires the /etc/salt/master.d/reactor.conf to do it automatically.  Manually, you have to kick off the stage 0 again.  I went with the reactor as the solution to this issue.

**Comment by rjfd** [comment]
But the reactor.conf present in the "master" branch as all lines commented, can you update the version you are using?

Moreover, even if the reactor starts again stage.0, it does not prevent the user from seeing his ssh connection to close without any notice.
This is the kind of issues that I think that can be better handled with the "frontend" application, by alerting the user that the system requires reboot, and ask for the user to run the deployment again.

**Comment by theanalyst** [comment]
I'm also kind of not sure whether we should always upgrade to the latest kernel, I assume this is something that we should discuss.. what about cases when there is a ptf/ fix released for a particular kernel and a newer kernel isn't what we want in the final product?

**Comment by rjfd** [comment]
@swiftgist, we cannot avoid the reboot. What we can do is alert the user that the current node where he is running the deployment needs to reboot. The frontend application should always run in the salt master node.

**Comment by swiftgist** [comment]
I have been leaving this issue open to add some sort of nice messaging prior to the reboot.  We need nice messages elsewhere as well.  Undecided on the best approach for Salt.

**Comment by swiftgist** [comment]
With 0.5.2, minions will now issue a wall command prior to the reboot.
