### ISSUE TITLE
Does engulf/upgrade check RBD client user caps?

### ISSUE THREAD

**Issue by smithfarm** [SUSE/DeepSea#640]
There is an upstream bug report [1] where "Three mailing list users have reported apparent filesystem corrupt post-upgrade to Luminous when using QEMU"

Jason just closed this by adding a bit to the Luminous release notes:

```
+#. Verify that all RBD client users have sufficient caps to blacklist
+   other client users. RBD client users with only ``"allow r"``
+   monitor caps shold to be updated as follows::
+
+     # ceph auth caps client.<ID> mon 'allow r, allow command "osd blacklist"'
+
```

Is there anything engulf/upgrade can do to ease the pain here?

[1] http://tracker.ceph.com/issues/21353

**Comment by jschmid1** [comment]
Currently we don't manage client keyrings. This might go into the docs.

**Comment by smithfarm** [comment]
The right doc for this is the luminous release notes, and it's there, so closing.
