### ISSUE TITLE
Stage 0: failed: Jinja error: 'validate.setup'

### ISSUE THREAD

**Issue by nchobisa** [SUSE/DeepSea#65]
Trying to run "salt-run state.orch ceph.stage.0" command get following error 
OS:- CentOS7
Compile:- DeepSea
[CRITICAL] Rendering SLS 'base:ceph.stage.0.master.default' failed: Jinja error: 'validate.setup'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 3, in top-level template code
  File "/usr/lib/python2.7/site-packages/salt/modules/saltutil.py", line 1181, in runner
    return rclient.cmd(name, kwarg=kwargs, print_event=False, full_return=True)
  File "/usr/lib/python2.7/site-packages/salt/runner.py", line 144, in cmd
    full_return)
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 225, in cmd
    self.functions[fun], arglist, pub_data
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1086, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python2.7/site-packages/salt/utils/lazy.py", line 101, in __getitem__
    raise KeyError(key)
KeyError: 'validate.setup'

; line 3

Any suggestion

**Comment by rjfd** [comment]
@nchobisa how did you installed DeepSea?

Check if the file `validate.py` is in `/srv/modules/runners` directory.

**Comment by jan--f** [comment]
Closing due to age. @nchobisa please re-open if issue still persists.

**Comment by nagarashish** [comment]
I am having same issue on centos 7.  validate.py is present in /srv/modules/runners.

Any idea how to resolve this issue?

**Comment by jan--f** [comment]
@nagarashish did you install DeepSea via the RPM or from the git repo? What salt version and DeepSea version are you using?

**Comment by nagarashish** [comment]
Followed instructions from: https://github.com/SUSE/DeepSea
1. Prepare Salt 
     Master
     --------
      salt-minion-2016.11.3-1.el7.noarch
      salt-master-2016.11.3-1.el7.noarch
      salt-repo-latest-1.el7.noarch
      salt-2016.11.3-1.el7.noarch

      Minion
      --------
     salt-minion-2016.11.3-1.el7.noarch
     salt-repo-latest-1.el7.noarch
     salt-2016.11.3-1.el7.noarch

2.  Install DeepSea
     -  Git clone https://github.com/SUSE/DeepSea.git
     -  make install
3.  Configure - make install automatically updated /srv/pillar/ceph/master_minion.sls.  
4.  Run salt-run state.orch ceph.stage.0 --> Getting Error in this step

**Comment by nagarashish** [comment]
Salt Master:
-------------
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
=====================================
salt-minion --versions-report
----------------------------------
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by swiftgist** [comment]
I just replied on #150, but I have not tried 2016.11.3 recently.  It is on my todo list.  Last year, I did see a Jinja related issue with 2016.11.3.  I have had success with 2015.8.12 and 2016.3.4.  Do you have any other Salt versions available?

**Comment by jan--f** [comment]
Closing this as duplicate to #150
