### ISSUE TITLE
 Exception occurred in runner validate.saltapi

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/DeepSea#651]
During first execution of deepsea stage run ceph.stage.0 I got this error at the end:

`validate.saltapi (/srv/modules/runners/validate.py):
  Exception occurred in runner validate.saltapi: Traceback (most recent call last):
    File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low
      data['return'] = self.functions[fun](*args, **kwargs)
    File "/srv/modules/runners/validate.py", line 929, in saltapi
      v.saltapi()
    File "/srv/modules/runners/validate.py", line 632, in saltapi
      result = json.loads(stdout[-1])
  IndexError: list index out of range
`
Subsequent executions do not show this error again.

Any idea what might have been causing this?

**Comment by swiftgist** [comment]
The curl command failed to verify that the Salt-api is answering.  We need to either add IndexError as another exception or just catch any exceptions.  

The intended error message is

```
Salt API is failing to authenticate - try 'systemctl restart salt-master'
```

but if it was fine all by itself, then I wonder if you simply had a slow responding salt-api.

**Comment by jschmid1** [comment]
re-open if this is still an issue
