### ISSUE TITLE
stage.4 stops and starts single iSCSI gateway without any changes to lrbd.conf

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/DeepSea#659]
When I execute the stage.4 the iSCSI gateway is stopped and started automatically even though there is only a single one and there was no change in lrbd.conf.

Could we adjust the iSCSI handling to apply changes only instead of a complete stop/start?

**Comment by swiftgist** [comment]
The short answer: yes.  I suspect we cannot use the watch mechanism in Salt similar to RGW.  But we did recently create a runner for detecting changes on the master and using that as a conditional for restarting RGW.

**Comment by jschmid1** [comment]
this is implemented via: https://github.com/SUSE/DeepSea/pull/632
