### ISSUE TITLE
doc description for Stage 0

### ISSUE THREAD

**Issue by swiftgist** [SUSE/DeepSea#66]
The provisioning comment is confusing.  It gives the impression to some that the OS can be installed.

I need a better word choice here to imply updates including kernel and potential reboots.  Other things like repo assignment are also possible.

**Comment by smithfarm** [comment]
@swiftgist Can you post a link to the doc in question?

**Comment by jan--f** [comment]
I think [this](https://github.com/SUSE/DeepSea/wiki/intro) is the doc in question. Why not use the name if the stage: Preparation. That is was is used in [another place](https://github.com/SUSE/DeepSea/wiki/management) in any case.

**Comment by swiftgist** [comment]
The wiki is updated now.
