### ISSUE TITLE
"urls" field is empty when running "salt-run ui rgw.credentials"

### ISSUE THREAD

**Issue by callithea** [SUSE/DeepSea#667]
Yesterday I deployed a new DeepSea cluster (via DS repo).
I tried to configure the salt-api and RGW settings via the openATTIC settings page and noticed that
it's not possible to enable the "Managed by DeepSea"-checkbox, since the salt-runner does not return the urls key.
See also: https://tracker.openattic.org/browse/OP-2704

**Comment by swiftgist** [comment]
This may be addressed by #682.  Think it's worth retrying on the next milestone.

**Comment by callithea** [comment]
@swiftgist: Thanks for letting me know, I'll try to update the cluster then.

**Comment by callithea** [comment]
Update: It worked for me after updating the cluster (git pull, make install & re-run of all stages).

**Comment by callithea** [comment]
Seems to be fixed with: https://github.com/SUSE/DeepSea/pull/682
