### ISSUE TITLE
DeepSea writes to cache directories under /srv/salt - these should be moved to /var/lib/salt

### ISSUE THREAD

**Issue by smithfarm** [SUSE/DeepSea#678]
https://github.com/SUSE/DeepSea/blob/b3ca5b06/Makefile#L525-L548

The packaging issue applies to all the cache directories that DeepSea writes to, i.e. ^^^

**Comment by smithfarm** [comment]
This would make our violations of `/srv` packaging guidelines [1] a bit less egregious.

[1] https://build.opensuse.org/request/show/503528

**Comment by swiftgist** [comment]
I didn't think that was the only packaging issue.  I thought having any files in /srv/pillar and /srv/salt seemed to upset them.

If we can restructure all of this, I think I prefer to do it all at once.  I know it's severe, but if all the sls files move from one tree to several others, we won't have several iterations of "where's this supposed to be?" and "what moved this week?".

**Comment by smithfarm** [comment]
Question answered, thanks.
