### ISSUE TITLE
status.report failing

### ISSUE THREAD

**Issue by swiftgist** [SUSE/DeepSea#697]
I am getting the following with 0.7.28

```
# salt-run status.report
  ceph: ceph version 12.2.0-398-g1264bae1a8 (1264bae1a8639e4ce83c0fdf96c23d1826009c2a) luminous (stable)
  os: SUSE Linux Enterprise Server 12 SP3
  salt: 2016.11.4

  mon3.ceph:
    ceph: Traceback (most recent call last):
  File "/usr/bin/ceph", line 125, in <module>
    import rados
ImportError: libceph-common.so.0: cannot map zero-fill pages
```

**Comment by jschmid1** [comment]
@swiftgist that's the message you get when you run out of memory.

**Comment by swiftgist** [comment]
Hmm, salt minions normally give me the "cannot allocate memory" message.  I'm not sure how we would capture that with a runner.  An ImportError happens for other reasons.

I'll close this, but the message is here in case somebody else hits it.
