### ISSUE TITLE
look into setting NTPD_FORCE_SYNC_ON_STARTUP

### ISSUE THREAD

**Issue by jan--f** [SUSE/DeepSea#71]
As @smithfarm pointed out "`/etc/sysconfig/ntp` has a knob (`NTPD_FORCE_SYNC_ON_STARTUP`) to make ntpd force clock sync at startup."

Maybe DeepSea setting this option improves a deployment with quicker clock sync.

**Comment by BlaineEXE** [comment]
While searching around the internet for this, I can't find any usage of `NTP_FORCE_SYNC_ON_STARTUP` that isn't SUSE-related. So we don't risk breaking NTP on non-suse linuxes, it would seem appropriate to gate this behind an OS check, yes?

```jinja
{% if salt['grains.get']('os').lower() == 'suse' '%}
    # set NTP_FORCE_SYNC_ON_STARTUP
{% endif %}
```

**Comment by swiftgist** [comment]
Sounds fine.  Grains are directly accessible from Jinja:

{% if grains['os_family'] == 'Suse' %}
{% if grains['os'] == 'SUSE' %}

I believe this will be the only use case in the sls file.  If CentOS, Ubuntu, etc. need similar settings and the Jinja is starting to overtake the file, then a module may be the way to go.  That can wait though until the need arises.

**Comment by jan--f** [comment]
I wonder how much we'll gain from this. If ntp is setup properly we won't have to sync on startup. Since this seems to be suse specific, I'd be in favour of not doing it.

**Comment by BlaineEXE** [comment]
As it seems to be (1) SUSE specific and (2) only 'maybe' improves deployment speed, I think this is something that we should at least table for later, though I'm not against closing this as an unaccepted feature.

**Comment by jan--f** [comment]
Yep I agree. I'll close this for now. We can always revisit if the need arises.
