### ISSUE TITLE
policy.cfg-generic

### ISSUE THREAD

**Issue by swiftgist** [SUSE/DeepSea#74]
The file is missing the stack/default entry.

The ultimate goal is to move this from the pillar entirely, but in the meantime, the examples should be accurate.

**Comment by jan--f** [comment]
@swiftgist still an issue? [policy.cfg-generic](https://github.com/SUSE/DeepSea/blob/master/doc/examples/policy.cfg-generic) looks ok to me?

**Comment by jan--f** [comment]
closing since it seems fixed.
