### ISSUE TITLE
lint refresh

### ISSUE THREAD

**Issue by swiftgist** [SUSE/DeepSea#753]
I have gone through the runners using pylint and would like everyone to come to a consensus.  I specifically made all the changes that I thought I could without any significant rewriting.  For those issues that are not neatly addressed, I add disables to the source.

I did skip the populate.py and benchmarks.py.  The first is slated to be remade as simply a role creator.  The second has active work and the linting can be addressed separately.

Take a look at https://github.com/SUSE/DeepSea/compare/wip-lint-refresh.  Definitely look at any of the runners you authored and decide if I added accurate doc strings.  

The nice thing about this exercise is that I see how each of us deviate from PEP naturally.  Changing vertical lines between functions and reordering imports do not phase me.  I will say I am undecided on whether the reformatting of some lines is an improvement for line length.  Also, several of us use single character variable names and I would argue appropriately.   However, I did change nearly every case of it.

I will say that my personal pet peeve is E124 that has to do with alignment.  PEP says you can do it two ways.  Pylint says otherwise.  Currently, I pulled the trailing ')' to the previous line to remove the warning.

Now, what do I need:  What and how will we use this?  I like simple rules and if we say that nothing shall be emitted from a pylint run on the file, that's easy to understand.  No confusion, no arguments.  Will we have a set of disables that we accept?  I find visually-indented-line-with-same-indent-as-next-logical-line acceptable because the alternatives are worse.  I also think too-few-public-methods works because we have several instances where we did not know how to share code between runners or consolidate.  All runners are not perfectly designed and it's okay.  The instances of no-self-use should likely be rewritten, but having this as a note works for now as do most of the inline disables.  When the next person comes along to extend or modify the functionality, address the pylint disables then.

I do like having the disables in the source.  No arguments about editors and what files need to be kept up to date where.  I will likely add a 'make lint' to the Makefile.

The other benefit to me is that any new disables will show up in a PR.  I do not expect any of us would have a paragraph of global disables or dozens of inline disables.  In general, I think few to several of either seems okay.  Neither is overwhelming.

The other important part is enabling this in Travis.  This is bound to slow down some submissions, but if the rules are simple that disables are allowed (especially in the catch-22 situations) then I do not see anything as a permanent blocker.

As far as tangible goals now, discussion is great, but I do need opinions with conclusions.  If single character variables are acceptable in some circumstances, then let's build a short list to later add to the wiki.  

I would also like to finish converting the modules and then turn this into a PR and merge it rather soon.  If anybody feels I vandalized some runner, let me know and I can revert that one.

**Comment by ddiss** [comment]
Your wip-lint-refresh branch looks good to me. I'm mostly coming from a K&R C background, so don't feel strongly about how things should be done in Python. The single letter variable ban seems a little harsh, but it should be relatively painless if all PRs are screened for 'make lint' errors.

**Comment by mogeb** [comment]
I agree with what you're suggesting. I sometimes use pylint as a plugin of my editor, and I do agree that's a good idea to start following its rules. Most importantly, being able and willing to disable some of them (given that we all agree on it) is also important IMO.

**Comment by jan--f** [comment]
The branch looks good to me. I'm not too worried about any particular detail as long as it converges towards some kind of consensus. Also thumbs up for having travis check.

**Comment by kmroz** [comment]
I like the idea of placing linter overrides within the source files themselves, but what if we agreed upon a few conventions of our own, and added them to a global ```lintrc``` file or equivalent?  Specifically, I'm thinking about parts of PEP8 that we wilfully want to override for the project.  This would form the basis for every new python file that gets added to DeepSea.  Further, we could link to this file from a DeepSea contribution wiki/readme, so that new comers are made aware of these conventions.

The first things that come to mind are:
  - line length
    - 90? 100?  And this too should not be a hard cap (further sensible overrides within source files _should_ be allowed/considered).
  - one letter variables
    - Sensible usage within loops, list comprehensions, etc. should be allowed.
  - alignment/continued indentation (E124)
    - As @swiftgist points out, opinions differ, I don't have a strong preference (and I've seen enough Lisp that )))))) doesn't really bother me) :wink:
  - tabs vs spaces
    - I think in general we use 4 spaces everywhere.  According to PEP8, python3 will not allow mixing of spaces and tabs (though I don't know at what level of granularity).  Enforcing 4 space tabs would be a good idea.

What do you guys think?  Any other conventions that you feel strongly about?

For the less common warnings (ie. too many returns in a function, too many nested if's, too few methods, unused vars, etc) it would be the developer's responsibility to refactor, or add an appropriate override to the file/class/function.

And as others have also mentioned, 👍 for adding this to travis.

**Comment by jan--f** [comment]
👍 for global lint file. Never a bad idea to make things explicit. I don't feel strongly about any of the listed convention but the last one. Python won't allow mixing tabs and spaces in a file. And I'd suggest we don't allow mixing in the code base in general. I.e. lets keep 4 space indents everywhere.

**Comment by smithfarm** [comment]
I don't have strong feelings about coding style, except that it should be unified within a given project, so I'm 100% in favor of this in general, especially since I can run the linter myself if needed.

Also, I agree with @jan--f about the tabs/spaces thing. Since tabs and spaces are visually indistinguishable, it's not easy to comply with policies if they call for the use of hard tabs.

**Comment by swiftgist** [comment]
So, if we pick a few things, add them to the lintrc, reference that on the contributions page, then we would not need to address them in each file.  I might do that in a separate PR just to make it obvious what became global.

With respect to tabs, I have been replacing them since very few files had them, but we did have a dozen or two lines that were all tab indented.

**Comment by kmroz** [comment]
All sounds good to me 👍

**Comment by swiftgist** [comment]
Okay.  I have PR #765 which has been rebased on master with lint and unit tests passing.  I would like to merge this and enable lint checks in Travis.

**Comment by swiftgist** [comment]
Fixed by #770
