### ISSUE TITLE
 Having error during a "salt-run state.orch ceph.stage.2"

### ISSUE THREAD

**Issue by IamAliBaba** [SUSE/DeepSea#762]
salt:~ # salt-run state.orch ceph.stage.2
[WARNING ] /usr/lib/python2.7/site-packages/salt/client/__init__.py:705: DeprecationWarning: The target type should be passed using the 'tgt_type' argument instead of 'expr_form'. Support for using 'expr_form' will be removed in Salt Fluorine.

public network           : 10.0.3.0/24
cluster network          : 10.0.3.0/24
[ERROR   ] Run failed on minions: salt
Failures:
    salt:
        Data failed to compile:
    ----------
        Rendering SLS 'base:ceph.mgr.key.default' failed: Jinja error: coercing to Unicode: need string or buffer, NoneType found
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 413, in render_jinja_tmpl
        output = template.render(**decoded_context)
      File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
        return self.environment.handle_exception(exc_info, True)
      File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "<template>", line 20, in top-level template code
      File "/var/cache/salt/minion/extmods/modules/keyring.py", line 13, in secret
        if os.path.exists(filename):
      File "/usr/lib64/python2.7/genericpath.py", line 26, in exists
        os.stat(path)
    TypeError: coercing to Unicode: need string or buffer, NoneType found

    ; line 20

    ---
    [...]
        - group: salt
        - mode: 600
        - makedirs: True
        - context:
          client: {{ client }}
          secret: {{ salt['keyring.secret'](keyring_file) }}    <======================
        - fire_event: True

    {% endfor %}

    [...]
    ---

salt_master:
  Name: push.proposal - Function: salt.runner - Result: Changed Started: - 07:56:46.795816 Duration: 1412.89 ms
  Name: refresh_pillar1 - Function: salt.state - Result: Changed Started: - 07:56:48.208880 Duration: 713.024 ms
  Name: advise.networks - Function: salt.runner - Result: Clean Started: - 07:56:48.922282 Duration: 1814.526 ms
  Name: admin key - Function: salt.state - Result: Clean Started: - 07:56:50.737050 Duration: 518.841 ms
  Name: mon key - Function: salt.state - Result: Changed Started: - 07:56:51.256075 Duration: 529.549 ms
----------
          ID: mgr key
    Function: salt.state
      Result: False
     Comment: Run failed on minions: salt
              Failures:
                  salt:
                      Data failed to compile:
                  ----------
                      Rendering SLS 'base:ceph.mgr.key.default' failed: Jinja error: coercing to Unicode: need string or buffer, NoneType found
                  Traceback (most recent call last):
                    File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 413, in render_jinja_tmpl
                      output = template.render(**decoded_context)
                    File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
                      return self.environment.handle_exception(exc_info, True)
                    File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
                      reraise(exc_type, exc_value, tb)
                    File "<template>", line 20, in top-level template code
                    File "/var/cache/salt/minion/extmods/modules/keyring.py", line 13, in secret
                      if os.path.exists(filename):
                    File "/usr/lib64/python2.7/genericpath.py", line 26, in exists
                      os.stat(path)
                  TypeError: coercing to Unicode: need string or buffer, NoneType found

                  ; line 20

                  ---
                  [...]
                      - group: salt
                      - mode: 600
                      - makedirs: True
                      - context:
                        client: {{ client }}
                        secret: {{ salt['keyring.secret'](keyring_file) }}    <======================
                      - fire_event: True

                  {% endfor %}

                  [...]
                  ---
     Started: 07:56:51.785863
    Duration: 2390.951 ms
     Changes:

Summary for salt_master
------------
Succeeded: 5 (changed=3)
Failed:    1
------------
Total states run:     6
Total run time:   7.380 s

Thnaks,
Ali

**Comment by jan--f** [comment]
Hi,
thanks for the report. What version of DeepSea are you using?

**Comment by IamAliBaba** [comment]
salt 'salt' pkg.version deepsea
salt:
    0.7.13-1.1

**Comment by jan--f** [comment]
oh wow...that is quite old. How did you get DeepSea to make a mgr key for you? This version has no support for mgr daemons.
I'd recommend you update DeepSea to the latest version.

**Comment by IamAliBaba** [comment]
could you advice me ?
i installed deepsea from RPM 
https://build.opensuse.org/package/binary/home:swiftgist/deepsea?arch=x86_64&filename=deepsea-0.7.13-1.1.noarch.rpm&repository=openSUSE_Leap_42.3

**Comment by jan--f** [comment]
You can find the latest package here https://build.opensuse.org/package/show/filesystems:ceph/deepsea

**Comment by IamAliBaba** [comment]
Thanks
during discovery stage i got this 


salt:~ # salt-run state.orch ceph.stage.1
[WARNING ] /usr/lib/python2.7/site-packages/salt/client/__init__.py:705: DeprecationWarning: The target type should be passed using the 'tgt_type' argument instead of 'expr_form'. Support for using 'expr_form' will be removed in Salt Fluorine.

**salt-api                 : ["Salt API is failing to authenticate - try 'systemctl restart salt-master'"]**
deepsea_minions          : valid
master_minion            : valid
ceph_version             : valid
[ERROR   ] No highstate or sls specified, no execution made
salt_master:
----------
          ID: salt-api failed
    Function: salt.state
        Name: just.exit
      Result: False
     Comment: No highstate or sls specified, no execution made
     Started: 06:57:24.854057
    Duration: 1.073 ms
     Changes:

Summary for salt_master
------------
Succeeded: 0
Failed:    1

**Comment by jan--f** [comment]
> salt-api: ["Salt API is failing to authenticate - try 'systemctl restart salt-master'"]

Try that maybe?

**Comment by IamAliBaba** [comment]
thanks,
i changed API port and it works.
now  i reached deploy step.
only remind coping ceph.conf and keying files .

**Comment by jschmid1** [comment]
Closed; Resolved
