### ISSUE TITLE
validate in populate.engulf_existing_cluster fails if python-configobj installed

### ISSUE THREAD

**Issue by tserong** [SUSE/DeepSea#767]
This one is a bit of fun:

````
# salt-run populate.engulf_existing_cluster
Exception occurred in runner populate.engulf_existing_cluster: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/srv/modules/runners/populate.py", line 1081, in engulf_existing_cluster
    validator = validate.Validate("ceph", local.cmd(search , 'pillar.items', [], expr_form="compound"),
AttributeError: 'module' object has no attribute 'Validate'
````

"WTF?" I hear you say, "`/srv/modules/runners/validate.py` has a Validate class, and this worked just fine yesterday."

Turns out I had python-configobj installed, which ships `/usr/lib/python2.7/site-packages/validate.py`, and it seems the `import validate` in `/srv/modules/runners/populate.py` picks up python-configobj's validate.py, not our `/srv/modules/runners/validate.py`.

python-configobj is a dependency of openATTIC, so once you've got openATTIC installed on your salt master, you can't run the engulfer anymore due to this conflict.

(python-configobj is also a dependency of diamond, but that's only likely to be installed if you've mangled an upgrade from a system with Calamari on it, which will presumably only happen to me.)

Is there some way we can qualify that `import`, so it grabs the correct validate.py?

**Comment by tserong** [comment]
Semi-randomly tagging @swiftgist, @kmroz, @rjfd -- any ideas? :-)

**Comment by kmroz** [comment]
Going with relative imports looks promising: https://www.python.org/dev/peps/pep-0328/#guido-s-decision

**Comment by rjfd** [comment]
what about:

```
from __future__ import absolute_imports

from .validate import Validate
```

Does it fixes the problem?

**Comment by kmroz** [comment]
@rjfd Yup, exactly what I had in mind. I just don’t have a cluster to test with (need to spool one up tomorrow, unless @tserong gets to it first).

**Comment by tserong** [comment]
Looks plausible :-) I can't test right now though (my cluster is somehow suddenly horribly broken for some completely unrelated reason)

**Comment by kmroz** [comment]
From what I understand of how relative imports work, they rely on a module's `__name__` to determine it's position within a package hierarchy.  In the case of our populate runner, it's `__name__` resolves to `salt.loaded.ext.runners.populate`.  Trying to perform a relative import of the validate runner, one level up from populate's position, will fail to find validate.py.

```
KM: salt.loaded.ext.runners.populate
[DEBUG   ] Failed to import runners populate:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1340, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/srv/modules/runners/populate.py", line 53, in <module>
    from . import validate
ImportError: cannot import name validate
```

This can also be confirmed locally with a simple module that tries to perform a relative import of a nonexistent source file.

Salt itself is loading/creating modules along with it's namespaces (LazyLoader) using various import builtins directly, making this story more interesting.  I'm not deeply familiar with the internals of Salt's module loading implementation.

What I've found that does work, is to perform an `imp.source_load` of validate.py as below.  I'd be lying if I said that I find this approach 'elegant'.

```
modified   srv/modules/runners/populate.py
@@ -48,7 +50,7 @@ import logging
 # pylint: disable=relative-import
 import deepsea_minions
 # pylint: disable=relative-import
-import validate
+import imp
 import operator

 import sys
@@ -1095,6 +1097,7 @@ def engulf_existing_cluster(**kwargs):
     # Make sure deepsea_minions contains valid minions before proceeding with engulf.
     minions = deepsea_minions.DeepseaMinions()
     search = minions.deepsea_minions
+    validate = imp.load_source('validate', '/srv/modules/runners/validate.py')
     validator = validate.Validate("ceph", local.cmd(search, 'pillar.items', [],
                                                     expr_form="compound"),
                                   [], validate.get_printer())
```

**Comment by tserong** [comment]
Ohgod.

Is it worth considering renaming validate to deepsea_validate or similar?

**Comment by kmroz** [comment]
Or.... wait for it....

**Comment by rjfd** [comment]
I found a solution by accident that fixes the issue.
Just move the `import validate` from the top of the file into the `engulf_existing_cluster(**kwargs)` function.
It worked in my setup.
