### ISSUE TITLE
HDDs could't be discovered

### ISSUE THREAD

**Issue by IamAliBaba** [SUSE/DeepSea#769]
Hi  All,  
Have anyone any idea why HDDs couldn't be discovered during  2nd step??  
I have   2 extra HDDs in each nodes .

Thanks,
Ali

**Comment by IamAliBaba** [comment]
salt:~/DeepSea # salt-run state.orch ceph.stage.1
[WARNING ] /usr/lib/python2.7/site-packages/salt/client/__init__.py:705: DeprecationWarning: The target type should be passed using the 'tgt_type' argument instead of 'expr_form'. Support for using 'expr_form' will be removed in Salt Fluorine.

deepsea_minions          : valid
master_minion            : valid
ceph_version             : valid
[WARNING ] All minions are ready
{'*': {'data': 0,
       'db-ratio': 5,
       'db-size': '500m',
       'encryption': '',
       'format': 'bluestore',
       'journal': 0,
       'journal-size': '5g',
       'leftovers': False,
       'name': 'default',
       'nvme-spinner': False,
       'nvme-ssd': False,
       'nvme-ssd-spinner': False,
       'ratio': 5,
       'ssd-spinner': False,
       'standalone': False,
       'wal': 0,
       'wal-size': '500m'}}
salt_master:
  Name: minions.ready - Function: salt.runner - Result: Changed Started: - 02:20:22.350185 Duration: 1465.32 ms
  Name: refresh_pillar0 - Function: salt.state - Result: Changed Started: - 02:20:23.815801 Duration: 405.096 ms
  Name: populate.proposals - Function: salt.runner - Result: Changed Started: - 02:20:24.221734 Duration: 4693.709 ms
  Name: proposal.populate - Function: salt.runner - Result: Changed Started: - 02:20:28.915816 Duration: 2298.842 ms

Summary for salt_master
------------
Succeeded: 4 (changed=4)
Failed:    0
------------
Total states run:     4
Total run time:   8.863 s

**Comment by jan--f** [comment]
Does ```salt '*' cephdisks.list``` report the disks you expect?

**Comment by IamAliBaba** [comment]
osd2:~ # salt-call cephdisks.list
local:

I got this

**Comment by jan--f** [comment]
Is this related to #758? Can you paste ```salt '*' -l debug cephdisks.list```?

**Comment by IamAliBaba** [comment]
Yes

**Comment by IamAliBaba** [comment]
osd1:~ # salt-call cephdisks.list -l debug
[DEBUG ] Reading configuration from /etc/salt/minion
[DEBUG ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG ] Including configuration from '/etc/salt/minion.d/mine_functions.conf'
[DEBUG ] Reading configuration from /etc/salt/minion.d/mine_functions.conf
[DEBUG ] Using cached minion ID from /etc/salt/minion_id: osd1
[DEBUG ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG ] Reading configuration from /etc/salt/minion
[DEBUG ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG ] Including configuration from '/etc/salt/minion.d/mine_functions.conf'
[DEBUG ] Reading configuration from /etc/salt/minion.d/mine_functions.conf
[WARNING ] Unable to find IPv6 record for "osd1" causing a 10 second timeout when rendering grains. Set the dns or /etc/hosts for IPv6 to clear this.
[DEBUG ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG ] Connecting to master. Attempt 1 of 1
[DEBUG ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'osd1', 'tcp://10.0.3.8:4506')
[DEBUG ] Generated random reconnect delay between '1000ms' and '11000ms' (3655)
[DEBUG ] Setting zmq_reconnect_ivl to '3655ms'
[DEBUG ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'osd1', 'tcp://10.0.3.8:4506', 'clear')
[DEBUG ] Decrypting the current master AES key
[DEBUG ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_3cae74d7a5_pub.ipc
[DEBUG ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_3cae74d7a5_pull.ipc
[DEBUG ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_3cae74d7a5_pull.ipc
[DEBUG ] Sending event: tag = salt/auth/creds; data = {'_stamp': '2017-11-06T14:20:33.127649', 'creds': {'publish_port': 4505, 'aes': 'X88NVFjh8z272bAvqCfQUkWdwxXV/LAsAJxodZvJkHIn9CnivQBna9ac1JRSofM4441l/R2XpQM=', 'master_uri': 'tcp://10.0.3.8:4506'}, 'key': ('/etc/salt/pki/minion', 'osd1', 'tcp://10.0.3.8:4506')}
[DEBUG ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG ] Determining pillar cache
[DEBUG ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'osd1', 'tcp://10.0.3.8:4506', 'aes')
[DEBUG ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'osd1', 'tcp://10.0.3.8:4506')
[DEBUG ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG ] LazyLoaded jinja.render
[DEBUG ] LazyLoaded yaml.render
[DEBUG ] LazyLoaded cephdisks.list
[INFO ] No raidctrl found
[DEBUG ] path: /sys/block/sda/device
[DEBUG ] path: /sys/block/sdb/device
[DEBUG ] path: /sys/block/sdc/device
[DEBUG ] Checking partitions ['1', '2', '3', '4'] on device /dev/sdc
[DEBUG ] path: /sys/block/sdd/device
[DEBUG ] path: /sys/block/sde/device
[DEBUG ] path: /sys/block/sdf/device
[DEBUG ] path: /sys/block/sr0/device
[DEBUG ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'osd1', 'tcp://10.0.3.8:4506', 'aes')
[DEBUG ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'osd1', 'tcp://10.0.3.8:4506')
[DEBUG ] LazyLoaded nested.output
local:

**Comment by jan--f** [comment]
ok then @jschmid1 is looking into this already. He'll need some more time to reproduce your environment I'm sure.

**Comment by IamAliBaba** [comment]
Thanks,
Could it connected with HDDs ?

**Comment by jschmid1** [comment]
Maybe that's connected to your HDD's. What model/type are these?

**Comment by IamAliBaba** [comment]
Model: "WDC WD3000BLFS-0"
Vendor: "WDC"
Device: "WD3000BLFS-0"
Revision: "4V06"
Serial ID: "WD-WXB1C10N9616"
Driver: "ahci", "sd"
Driver Modules: "ahci", "sd_mod"

**Comment by jschmid1** [comment]
Is some kind of hardware raidcontroller involved. Are these standard harddisks or solid states?

**Comment by jschmid1** [comment]
an output of:

`lsblk`

would also help

**Comment by IamAliBaba** [comment]
They are SAS drives 10K

**Comment by IamAliBaba** [comment]
problem is from HDD side.

**Comment by IamAliBaba** [comment]
Solved!!!

Thanks to all,
-Ali

**Comment by jschmid1** [comment]
great to hear. closing
