### ISSUE TITLE
populate.proposal creates unnecessary files

### ISSUE THREAD

**Issue by jan--f** [SUSE/DeepSea#772]
For roles mon an igw the populate runner still creates yml files with public_address settings in them.

**Comment by tserong** [comment]
I got rid of that piece from the policy wiki page too: https://github.com/SUSE/DeepSea/wiki/policy/_compare/53fc1af4e555e5d2eebdae4f0b96e4b2e1404e30...5281e1d5f5839eeb35e7b144b7a0a51f3cf91cc5
