### ISSUE TITLE
openATTIC settings configuration: "Object Gateway API connection failed"

### ISSUE THREAD

**Issue by callithea** [SUSE/DeepSea#783]
Error message: "Non system user capabilities, or wrong admin resource path"
I was able to reproduce this behavior twice (fresh DeepSea setup based on master branch, commit ded2b14da1b97218bd6b7efeefbf2da668a06727).
Fixed this manually by modifying the admin user and setting "system" to true with radosgw-admin.
From ceph -s output:
```
health: HEALTH_OK
rgw:     1 daemon active
```

ceph version: ceph version 12.2.1-361-gaea79b8b7a (aea79b8b7a65a8ca5cc1de84c7fe7d99eaa72ec0) luminous (stable)

Anyone else with this issue?

**Comment by sebastian-philipp** [comment]
https://tracker.openattic.org/browse/OP-2916
