### ISSUE TITLE
deploy ceph by deepsea failed at stage 0

### ISSUE THREAD

**Issue by losemyheaven** [SUSE/DeepSea#798]
In opensuse 42.3, deepsea fails to deploy ceph. Failure occured at stage 0.
This is the output.
[deubg.txt](https://github.com/SUSE/DeepSea/files/1491118/deubg.txt)
or see this gist
https://gist.github.com/losemyheaven/8c9a70f1bc6368a7291035ddbc888e6a

**Comment by rjfd** [comment]
@losemyheaven I've seen this problem when running the current DeepSea version using the latest Salt version 2017.*. Can paste the Salt version you're using?

**Comment by losemyheaven** [comment]
@rjfd this is my salt version  
salt 2017.7.2 (Nitrogen)
Thanks

**Comment by rjfd** [comment]
@losemyheaven there is already a fix for that problem but it's included in a non-related PR #795

Probably it makes sense to fix this in a different PR if #795 takes too long to be merged.
Let's leave this issue open to track this problem.

**Comment by losemyheaven** [comment]
@rjfd is there any workarond?

**Comment by rjfd** [comment]
@losemyheaven you can install DeepSea from source using the branch of PR #795 if you are in development/testing environment.

Follow these instructions in the salt-master node:

```
git clone https://github.com/rjfd/DeepSea.git
cd DeepSea
git checkout wip-centos
make install
```

**Comment by losemyheaven** [comment]
@rjfd I tried to followed your instructions, but it got stuck on make install,
when running a step of make install -----------"salt-api python-ipaddress",

**Comment by rjfd** [comment]
@losemyheaven `make install` is trying to install `salt-api` and `python-ipaddress` packages.

Try to install these manually with zypper:

`zypper install salt-api python-ipaddress`

**Comment by losemyheaven** [comment]
@rjfd I still got the same result.
salt-api and python-ipaddress has already been installed.



chown root:root /srv/salt/ceph/rgw/cache || true
chown root:root /srv/salt/ceph/configuration/files/ceph.conf.checksum || true
sed -i '/^sharedsecret: /s!{{ shared_secret }}!'`cat /proc/sys/kernel/random/uuid`'!' /etc/salt/master.d/sharedsecret.conf
chown root:root /etc/salt/master.d/*
echo "deepsea_minions: '*'" > /srv/pillar/ceph/deepsea_minions.sls
chown -R root /srv/pillar/ceph
sed -i '/^master_minion:/s!_REPLACE_ME_!'`cat /etc/salt/minion_id`'!' /srv/pillar/ceph/master_minion.sls
systemctl restart salt-master
salt-api python-ipaddress

**Comment by rjfd** [comment]
@losemyheaven I think you might have found another bug :)

Can you paste the output of this command: `egrep ^ID= /etc/os-release | sed -e 's/ID="\(.*\)"/\1/g'`

Also, the only thing you need to finish the install is run the following commands:
```
systemctl restart salt-api
zypper -n install python-setuptools python-click
python setup.py install
```

**Comment by losemyheaven** [comment]
@rjfd ID=opensuse

```
systemctl restart salt-api
zypper -n install python-setuptools python-click
python setup.py install
```
After running these, I still got stuck on `salt-api python-ipaddress`

**Comment by rjfd** [comment]
@losemyheaven `salt-api python-ipaddress` is a bug generated by the Makefile code. At the step you are, you are already prepared to start run stage 0.

Run stage 0 with this command:

`deepsea stage run ceph.stage.0`

**Comment by losemyheaven** [comment]
@rjfd I also found this bug, this bug is because makefile's several starting lines, where PKG_INSTALL var is defined.
I'll try to fix this bug and then go ahead.

**Comment by rjfd** [comment]
@losemyheaven to fix that bug just change line 4 of Makefile to:

`OS=$(shell egrep ^ID= /etc/os-release | sed -e 's/ID="\{0,1\}\(\w*\)"\{0,1\}/\1/g')`

**Comment by smithfarm** [comment]
@rjfd I always wonder, when confronted with code that parses `/etc/os-release` using sed, awk, etc., whether it would be possible to eliminate that code by simply sourcing `/etc/os-release` as was originally intended. For example

```
OS=$(source /etc/os-release ; echo $ID)
```

**Comment by rjfd** [comment]
@smithfarm haha, you're so right! my bad. Although this is inside a makefile and I need to find how to `source` a file.

Can you add your previous comment as a review to PR #795 ?

**Comment by losemyheaven** [comment]
@smithfarm 
Nice code, really!!!

**Comment by smithfarm** [comment]
> Although this is inside a makefile

Yeah. . . one way would be to write a script that sources `/etc/os-release` and then runs make. Like upstream ceph has (`do_cmake.sh`).

**Comment by losemyheaven** [comment]
but in makefile, it should be
```
OS=$(shell source /etc/os-release ; echo $$ID)
```

**Comment by losemyheaven** [comment]
Could I try to pull request for this bug??

**Comment by rjfd** [comment]
@losemyheaven I'm already fixing in the PR...

**Comment by losemyheaven** [comment]
@rjfd Haha, thanks

**Comment by losemyheaven** [comment]
@rjfd 
still got failures
https://gist.github.com/losemyheaven/8c9a70f1bc6368a7291035ddbc888e6a

**Comment by rjfd** [comment]
@losemyheaven this is great, you're hitting several bugs because I didn't test the PR agains openSUSE.

can you paste the output of:

`salt-call pkg.installed kernel-default`

**Comment by losemyheaven** [comment]
@rjfd 
'pkg.installed' is not available.

**Comment by rjfd** [comment]
@losemyheaven sorry it's `pkg.info_installed`

**Comment by losemyheaven** [comment]
local:
    ----------
    kernel-default:
        ----------
        arch:
            x86_64
        build_date:
            2017-10-22T18:40:46Z
        build_date_time_t:
            1508697646
        build_host:
            lamb66
        description:
            The standard kernel for both uniprocessor and multiprocessor systems.


            Source Timestamp: 2017-10-22 08:56:24 +0200
            GIT Revision: 1d80e8ae891703b5b43208ed51c1e9b82fbffae4
            GIT Branch: openSUSE-42.3
        group:
            System/Kernel
        install_date:
            2017-11-21T10:57:44Z
        install_date_time_t:
            1511261864
        license:
            GPL-2.0
        packager:
            http://bugs.opensuse.org
        release:
            31.1
        relocations:
            (not relocatable)
        signature:
            RSA/SHA256, Sun Oct 22 18:44:56 2017, Key ID b88b2fd43dbdc284
        size:
            246920610
        source:
            kernel-default-4.4.92-31.1.nosrc.rpm
        summary:
            The Standard Kernel
        url:
            http://www.kernel.org/
        vendor:
            openSUSE
        version:
            4.4.92

**Comment by losemyheaven** [comment]
@rjfd orry to trouble you...

**Comment by rjfd** [comment]
@losemyheaven I've update the "wip-centos" branch with a fix to the problem you're getting. (It also includes the makefile fix)

Fetch that branch again, and run make install

**Comment by losemyheaven** [comment]
@rjfd sorry, I'll try tomorrow, it's too late, I have to go home now...

**Comment by losemyheaven** [comment]
stage end up with salt master node's reboot, 
but when run stage 2, trouble occured..

```
> 
[WARNING ] /usr/lib/python2.7/site-packages/salt/client/__init__.py:705: DeprecationWarning: The target type should be passed using the 'tgt_type' argument instead of 'expr_form'. Support for using 'expr_form' will be removed in Salt Fluorine.

salt-api                 : ["Salt API is failing to authenticate - try 'systemctl restart salt-master': No JSON object could be decoded"]

^[[B^[[C[ERROR   ] No highstate or sls specified, no execution made
salt_master:
----------
          ID: salt-api failed
    Function: salt.state
        Name: just.exit
      Result: False
     Comment: No highstate or sls specified, no execution made
     Started: 23:22:18.766577
    Duration: 1.129 ms
     Changes:   

Summary for salt_master
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   1.129 ms
```

**Comment by rjfd** [comment]
@losemyheaven when you ran stage 0 was every step successful?

**Comment by losemyheaven** [comment]
@rjfd nothing output
I connect salt node by ssh. It output nothing, and finally reboot.

**Comment by rjfd** [comment]
@losemyheaven make sure that `/etc/salt/master.d/sharedsecret.conf` contains the salt-api secret key correctly configured. Something like: `sharedsecret: xxxxxxx-xxxx-xxxx-xxxx-xxx...`

Then restart the salt-api daemon: `systemctl restart salt-api`

Did stage 1 run successfully? 
Did you create the `policy.cfg` file after stage 1 but before running stage 2?

I would suggest you to run the stages using the deepsea-cli which gives a much more user-friendly view of the errors and also shows you the stage progress in real-time.
Example: `deepsea stage run ceph.stage.2`

**Comment by losemyheaven** [comment]
@rjfd I'm sure that stage succeeded.
```
salt:~ # salt-run state.orch ceph.stage.0
[WARNING ] /usr/lib/python2.7/site-packages/salt/client/__init__.py:705: DeprecationWarning: The target type should be passed using the 'tgt_type' argument instead of 'expr_form'. Support for using 'expr_form' w
ill be removed in Salt Fluorine.

deepsea_minions          : valid
master_minion            : valid
ceph_version             : valid
[WARNING ] All minions are ready
salt_master:
  Name: salt-api - Function: salt.state - Result: Changed Started: - 17:13:05.363544 Duration: 2191.127 ms
  Name: sync master - Function: salt.state - Result: Changed Started: - 17:13:07.554861 Duration: 867.838 ms
  Name: repo master - Function: salt.state - Result: Clean Started: - 17:13:08.422915 Duration: 463.308 ms
  Name: prepare master - Function: salt.state - Result: Changed Started: - 17:13:08.886523 Duration: 30770.742 ms
  Name: filequeue.remove - Function: salt.runner - Result: Clean Started: - 17:13:39.657692 Duration: 963.033 ms
  Name: restart master - Function: salt.state - Result: Clean Started: - 17:13:40.620962 Duration: 2063.552 ms
  Name: filequeue.add - Function: salt.runner - Result: Changed Started: - 17:13:42.684874 Duration: 1607.19 ms
  Name: minions.ready - Function: salt.runner - Result: Changed Started: - 17:13:44.292253 Duration: 1973.22 ms
  Name: repo - Function: salt.state - Result: Clean Started: - 17:13:46.265694 Duration: 592.849 ms
  Name: common packages - Function: salt.state - Result: Clean Started: - 17:13:46.858904 Duration: 2045.844 ms
  Name: sync - Function: salt.state - Result: Changed Started: - 17:13:48.905114 Duration: 1414.536 ms
  Name: mines - Function: salt.state - Result: Changed Started: - 17:13:50.319909 Duration: 3482.935 ms
  Name: updates - Function: salt.state - Result: Changed Started: - 17:13:53.803033 Duration: 27826.979 ms
  Name: restart - Function: salt.state - Result: Clean Started: - 17:14:21.630202 Duration: 3253.293 ms

Summary for salt_master
-------------
Succeeded: 14 (changed=8)
Failed:     0
-------------
Total states run:     14
Total run time:   79.516 s
```

Content in sharedsecret.conf is same as you said
```
sharedsecret: 56093bc8-49c5-4261-a8c2-f928638ac965
```

Unfortunately, After restart salt-api service on salt master node, I still got the prompt as
```
[WARNING ] /usr/lib/python2.7/site-packages/salt/client/__init__.py:705: DeprecationWarning: The target type should be passed using the 'tgt_type' argument instead of 'expr_form'. Support for using 'expr_form' w
ill be removed in Salt Fluorine.                                                                                 
                                                                                                                
salt-api                 : ["Salt API is failing to authenticate - try 'systemctl restart salt-master': No JSON object could be decoded"]
^C[ERROR   ] No highstate or sls specified, no execution made                                                   
salt_master:                                                                                                   
----------                                                                                                      
          ID: salt-api failed                                                                                     
    Function: salt.state                                                                              
        Name: just.exit                                                                                            
      Result: False                                                                                       
     Comment: No highstate or sls specified, no execution made                                         
     Started: 17:16:02.608945                                                                               
    Duration: 0.916 ms 
     Changes:        
                         
Summary for salt_master                 
------------                              
Succeeded: 0            
Failed:    1              
------------                                
Total states run:     1                                                                                                                                                                                            
Total run time:   0.916 ms 
```

**Comment by rjfd** [comment]
@losemyheaven Ok, so there is some problem with the salt-api daemon that we need to solve.



First, paste the output of `/etc/salt/master.d/salt-api.conf`. Then, check if you can access port 8000 in your salt-master using a web browser or using curl in the terminal.

The curl command should be something like this:
```
curl -sSk http://salt:8000/login -c /tmp/ds-runner-cookies.txt \
    -H 'Accept: application/json' -d username=admin \
    -d sharedsecret=56093bc8-49c5-4261-a8c2-f928638ac965 \
    -d eauth=sharedsecret
```

The above command should return something like this:
```
```

**Comment by losemyheaven** [comment]
@rjfd really appreciate your help. Thanks.
```
salt:~ # cat /etc/salt/master.d/salt-api.conf

rest_cherrypy:
  port: 8000
  disable_ssl: True
```

```
salt:~ # curl -sSk http://salt:8000/login -c /tmp/ds-runner-cookies.txt \
>     -H 'Accept: application/json' -d username=admin \
>     -d sharedsecret=56093bc8-49c5-4261-a8c2-f928638ac965 \
>     -d eauth=sharedsecret
<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>503 Service Unavailable</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>503 Service Unavailable</h2>
        <p>Salt Master is not available.</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 3.6.0</a>
      </span>
    </div>
    </body>
</html>

```

**Comment by rjfd** [comment]
@losemyheaven from the output of the curl command looks that there is some problem in the communication between the salt-api and the salt-master.

Restart both daemons and try again. `systemctl restart salt-api salt-master`

If the problem persists we need to get information from the salt-master logs. For that, change the log level in `/etc/salt/master` to `debug` (search for the option `log_level`), restart the salt-master, and repeat that curl command. Then check the log in `/var/log/salt/master` and see if some error is present.

**Comment by losemyheaven** [comment]
Yeah, the problem reoccured.
```
salt:/var/log/salt # curl -sSk http://salt:8000/login -c /tmp/ds-runner-cookies.txt \
>     -H 'Accept: application/json' -d username=admin \
>     -d sharedsecret=56093bc8-49c5-4261-a8c2-f928638ac965 \
>     -d eauth=sharedsecret
<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>503 Service Unavailable</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>503 Service Unavailable</h2>
        <p>Salt Master is not available.</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 3.6.0</a>
      </span>
    </div>
    </body>
</html>

```

and this is master log
https://gist.github.com/losemyheaven/1934df4bc17fe5912ebae653c3ceed7a

**Comment by rjfd** [comment]
@losemyheaven paste the contents of `/var/log/salt/api`

**Comment by losemyheaven** [comment]
@rjfd 
```
2017-11-21 20:32:31,126 [salt.utils.parsers][WARNING ][4201] SaltAPI received a SIGINT. Exiting.                                                                                                                   
2017-11-21 20:50:44,492 [salt.utils.parsers][WARNING ][5895] SaltAPI received a SIGINT. Exiting.
2017-11-21 21:14:19,827 [salt.utils.parsers][WARNING ][7646] SaltAPI received a SIGINT. Exiting.
2017-11-21 21:27:24,509 [salt.utils.parsers][WARNING ][9505] SaltAPI received a SIGINT. Exiting.
2017-11-21 21:29:23,145 [salt.utils.parsers][WARNING ][11096] SaltAPI received a SIGINT. Exiting.
2017-11-21 21:51:43,638 [cherrypy.error   ][ERROR   ][14502] [21/Nov/2017:21:51:43] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7fa46d48fa50>>
Traceback (most recent call last):                                        
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 205, in publish
    output.append(listener(*args, **kwargs))         
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpserver.py", line 168, in start
    ServerAdapter.start(self)              
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 170, in start
    wait_for_free_port(*self.bind_addr)
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 438, in wait_for_free_port
    raise IOError("Port %r not free on %r" % (port, host))
IOError: Port 8000 not free on '0.0.0.0'     
                                                            
2017-11-21 21:51:43,639 [cherrypy.error   ][ERROR   ][14502] [21/Nov/2017:21:51:43] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):                                           
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 243, in start
    self.publish('start')                                       
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 223, in publish
    raise exc                                                       
ChannelFailures: IOError("Port 8000 not free on '0.0.0.0'",)

2017-11-21 21:51:43,639 [cherrypy.error   ][ERROR   ][14502] [21/Nov/2017:21:51:43] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):                                           
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 243, in start
    self.publish('start')                                       
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 223, in publish
    raise exc                                                       
ChannelFailures: IOError("Port 8000 not free on '0.0.0.0'",)
                                                                
2017-11-21 21:51:48,710 [salt.utils.parsers][WARNING ][14491] SaltAPI received a SIGINT. Exiting.
2017-11-21 21:52:11,442 [cherrypy.error   ][ERROR   ][15680] [21/Nov/2017:21:52:11] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7f91330b3a50>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 205, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpserver.py", line 168, in start
    ServerAdapter.start(self)                                                                                                                                                                              
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 170, in start                                                                                                                     
    wait_for_free_port(*self.bind_addr)
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 438, in wait_for_free_port
    raise IOError("Port %r not free on %r" % (port, host))
IOError: Port 8000 not free on '0.0.0.0'
                            
2017-11-21 21:52:11,442 [cherrypy.error   ][ERROR   ][15680] [21/Nov/2017:21:52:11] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 243, in start
    self.publish('start')
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 223, in publish
    raise exc
ChannelFailures: IOError("Port 8000 not free on '0.0.0.0'",)

2017-11-21 21:52:14,296 [salt.utils.parsers][WARNING ][15669] SaltAPI received a SIGINT. Exiting.

```

**Comment by rjfd** [comment]
@losemyheaven looks like some other process is already using port 8000 in that node, and that prevents salt-api from working.

**Comment by losemyheaven** [comment]
@rjfd 
salt:/srv/salt # lsof -i :8000
COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
salt-api 13078 salt    8u  IPv4 204106      0t0  TCP *:irdmi (LISTEN)

**Comment by rjfd** [comment]
@losemyheaven 

kill that process, and also run `systemctl stop salt-api`. Then run `lsof -i :8000` again and check that no process is using port 8000.
After this start salt-api daemon using systemctl and check the `/var/log/salt/api` to see if there is any error.

**Comment by losemyheaven** [comment]
@rjfd it's not a problem of 8000 port occupied.
The /var/log/salt/api shows yesterday's log, but nothing about today(2017-11-22)
After killing the process, still prompt
```
[INFO    ] VALIDATE ERROR   salt-api                 : ["Salt API is failing to authenticate - try 'systemctl restart salt-master': No JSON object could be decoded"]
salt-api                 : ["Salt API is failing to authenticate - try 'systemctl restart salt-master': No JSON object could be decoded"]  
...........
[DEBUG   ] Sending event: tag = salt/run/20171122185116684357/ret; data = {'fun_args': ['ceph.stage.1'], 'jid': '20171122185116684357', 'return': {'outputter': 'highstate', 'data': {'salt_master': {'salt_|-salt-
api failed_|-just.exit_|-state': {'comment': 'No highstate or sls specified, no execution made', 'name': 'just.exit', 'start_time': '18:51:49.634329', 'result': False, 'duration': 1.398, '__run_num__': 0, '__sls
__': u'ceph.stage.1.default', 'changes': {}, '__id__': 'salt-api failed'}}}, 'retcode': 1}, 'success': False, '_stamp': '2017-11-22T10:51:49.640783', 'user': 'root', 'fun': 'runner.state.orch'}
[DEBUG   ] LazyLoaded highstate.output                                                                                                                                                                             
salt_master:                                                                                                                                
----------                                                                                                                               
          ID: salt-api failed                                                                 
    Function: salt.state                                                                                                                    
        Name: just.exit                                                                                                                  
      Result: False                                                                         
     Comment: No highstate or sls specified, no execution made                                                                                                                                                     
     Started: 18:51:49.634329                                                                                                                
    Duration: 1.398 ms                                                                                                                   
     Changes:                                                                                                                                                                                                      
                                                                                                                                            
Summary for salt_master                                                                                                                  
------------                                                                                                                                                                                                       
Succeeded: 0                                                                                                                                 
Failed:    1                                                                                  
------------                                                                                                                                                                                                       
Total states run:     1                                                                                                                      
Total run time:   1.398 ms  
```

**Comment by rjfd** [comment]
@losemyheaven do you still have the salt-master log_level set to "debug"? There's something misconfigured in your environment that is preventing salt-api from working properly.

I'm running out of ideas...

**Comment by losemyheaven** [comment]
@rjfd yes, log_level in /etc/salt/master is still "debug"
I turned it off, and restart salt api and salt master services, 
problem still happened.

**Comment by losemyheaven** [comment]
@rjfd 
Thanks for your help. And sorry for that it cost you two days. 
Just forget it.
I'll try to read the source code and find why.

Thanks,
Larry

**Comment by IamAliBaba** [comment]
Hello guys,

The same error i had.

During that step change salt-api port and do reboot, after that try the step again. it will work, but when you will try to connect ceph cluster and openATTIC , you will get that error again.

**Comment by losemyheaven** [comment]
@IamAliBaba 
Unfortunately, this problem is still not fixed.
...
Actually, I gave up.

**Comment by IamAliBaba** [comment]
Hello,
thats why i am using centos 7 for admin node

**Comment by losemyheaven** [comment]
@IamAliBaba 
Does centos 7 work??

**Comment by IamAliBaba** [comment]
yes, 
Im using centos7 and 4 opensuse storage nodes.

**Comment by losemyheaven** [comment]
@IamAliBaba 
Have you tried to deploy openattic on you centos??

**Comment by IamAliBaba** [comment]
no, openattic node is another one

**Comment by losemyheaven** [comment]
@IamAliBaba 
How did you deploy openattic?  with which distribution?

**Comment by IamAliBaba** [comment]
opensuse leap 43.2

**Comment by losemyheaven** [comment]
just zypper in openattic??
@IamAliBaba

**Comment by IamAliBaba** [comment]
wait i can post all instruction

**Comment by IamAliBaba** [comment]
do you want centos deepsea RPM ?

**Comment by losemyheaven** [comment]
You build deepsea RPM by yourself?
I need instructions :-)

**Comment by IamAliBaba** [comment]
wait 5 min , i will post

**Comment by IamAliBaba** [comment]
zypper ar https://download.opensuse.org/repositories/filesystems:/ceph:/luminous/openSUSE_Leap_42.3/ ceph-L (on all opensuse nodes)
zypper ar https://download.opensuse.org/repositories/filesystems:/openATTIC:/3.x/openSUSE_Leap_42.3/ openattic (on all opensuse nodes)
zypper ar https://download.opensuse.org/repositories/systemsmanagement:/saltstack:/products/openSUSE_Leap_42.3/  salt (on all opensuse nodes)
zypper in https://download.opensuse.org/repositories/home:/swiftgist/openSUSE_Leap_42.3/noarch/lrbd-1.3-2.1.noarch.rpm (on all opensuse nodes)
zypper ref (on all opensuse nodes)
zypper in salt-minon (on all opensuse nodes)
nano /etc/salt/minion (on all opensuse nodes)
"master: salt.example.com"
systemctl enable salt-minion (on all opensuse nodes)
systemctl start salt-minion (on all opensuse nodes)
zypper dup (on all opensuse nodes)
reboot (on all opensuse nodes)



yum install epel-release -y 
nano /etc/yum.repos.d/deepsea.repo
"
[rjdias-home]
name=Copr repo for home owned by rjdias
baseurl=https://copr-be.cloud.fedoraproject.org/results/rjdias/home/epel-7-$basearch/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/rjdias/home/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1
"
yum update -y
sudo yum install -y  https://repo.saltstack.com/yum/redhat/salt-repo-latest-2.el7.noarch.rpm
yum install -y salt-minion salt-master (make sure salt is latest version )
nano /etc/salt/minion
"master: salt.example.com"
systemctl enable salt-minion 
systemctl start salt-minion 
yum install deepsea (version 8.0)
yum install https://download.ceph.com/rpm-luminous/el7/noarch/ceph-release-1-1.el7.noarch.rpm
yum install -y ntp sntp sntp ntpdate ntp-doc
ntpdate 0.us.pool.ntp.org
hwclock --systohc
systemctl enable ntpd.service
systemctl start ntpd.service
systemctl enable sntp
systemctl start sntp

reboot


salt-run state.orch ceph.stage.0
salt-run state.orch ceph.stage.1
salt-run state.orch ceph.stage.2
salt-run state.orch ceph.stage.3

**Comment by losemyheaven** [comment]
@IamAliBaba 
Really appreciate your help!!!
I'll try later.

**Comment by IamAliBaba** [comment]
during stages ignore python-boto filed . its ok ,

**Comment by IamAliBaba** [comment]
if will need help . feel free to ask

-Ali.

**Comment by losemyheaven** [comment]
@IamAliBaba 
Could you please leave your email address?

**Comment by IamAliBaba** [comment]
davtyan_karen skype

**Comment by losemyheaven** [comment]
@IamAliBaba 
thanks~~

**Comment by IamAliBaba** [comment]
Hi @rjfd ,

i wonder will you publish new release for this,
https://copr.fedorainfracloud.org/coprs/rjdias/home/packages/

thanks

**Comment by IamAliBaba** [comment]
bug found .
salt-2017 is the problem .

try to use 2016 and yeverything will be ok

**Comment by jschmid1** [comment]
resolved.
