### ISSUE TITLE
Granfana and Prometheus configs should be moved into a dedicated repository

### ISSUE THREAD

**Issue by sebastian-philipp** [SUSE/DeepSea#799]
Use case: A user of openATTIC wants to use monitory without a cluster deployed by DeepSea. he then has to fiddle out the exporters and dashboards out of the DeepSea repository and apply them manually. 

It would be awesome to have the exporters and dashboards in a dedicated location in order to simplify installation without DeepSea. 

See also: [OP-2791](https://tracker.openattic.org/browse/OP-2791)

**Comment by jan--f** [comment]
Not sure how this is a DeepSea issue. If you want to setup the monitoring outside of deepsea this requires code outside of deepsea.
