### ISSUE TITLE
fqdn and localhost

### ISSUE THREAD

**Issue by swiftgist** [SUSE/DeepSea#80]
The validation step checks to see that the minion name matches the fqdn for each salt minion.  The objective is to eliminate the confusion between "ping nodeA" and "salt 'minionX.domain' test.ping" when these are the same server.  Those new to Salt start support issues of "why doesn't "salt 'nodeA' test.ping" work?"

If your setup includes adding the hostname to /etc/hosts as 127.0.0.1, then the salt minion will list the fqdn as localhost.  I believe Salt is relying on python and that a forward and reverse lookup are involved.  

The question is "Is localhost a valid fqdn for Salt?".  I cannot think of any consequences currently.  If that is the case, then validate.py needs to allow "localhost" as a match for any fqdn.

**Comment by theanalyst** [comment]
This seems to be an issue with the way upstream salt itself populates the fqdn grain, not matching the `hostname -f`, as one would expect, a detailed issue is here https://github.com/saltstack/salt/issues/36619

**Comment by theanalyst** [comment]
Secondly we don't seem to use the value of `grains.fqdn` anywhere else either

**Comment by theanalyst** [comment]
Alternatively if we don't error and just warn instead wouldn't that be okay?

**Comment by swiftgist** [comment]
I think I still prefer the error on nodeA doesn't match minionX until somebody has a real use case where this is a problem.  I agree that 'localhost' could just generate a warning and continue.

**Comment by theanalyst** [comment]
Addressed this in #84
