### ISSUE TITLE
render SLS file fails when `slspath` jinja variable is used

### ISSUE THREAD

**Issue by rjfd** [SUSE/DeepSea#814]
If deepsea-cli is parsing/rendering an SLS file that uses the `{{ slspath }}` jinja variable it fails with the following error:

```
Error description:
SaltRenderError: Jinja variable 'slspath' is undefined
```

The problem is caused by the use of the module `cp.get_template` which renders an SLS file but it does not have all the jinja variables in its context.

The CLI render/parser engine must be able to cope with the presence of these jinja variables.

**Comment by jschmid1** [comment]
fixed by #1149
