### ISSUE TITLE
qa: make test scripts take a "--no-reboot" option

### ISSUE THREAD

**Issue by smithfarm** [SUSE/DeepSea#818]
All the test scripts under `qa/` should take a `--no-reboot` option which would activate the `default-no-update-no-reboot.sls` alternative default for Stage 0.

**Comment by smithfarm** [comment]
@rjfd `deepsea stage run` does not yet implement a `--no-reboot` option, correct?

**Comment by rjfd** [comment]
@smithfarm that's correct.

**Comment by jschmid1** [comment]
Deepsea now defaults to no-reboot
