### ISSUE TITLE
stop setting rgw dns name

### ISSUE THREAD

**Issue by theanalyst** [SUSE/DeepSea#842]
We set the `rgw dns name` configurable as the node's fqdn. However most deployments seem to have multiple rgw endpoints and the fqdn not set up correctly in the node to match the dns name. Without this set, all of the S3 and swift apis should still work correctly except when a bucket style access is used which s3 clients like s3cmd default to. But for these clients even after an fqdn setting they would require dnsmasq configured in the client side correctly, so people making this deployment step anyway cannot just use the default out of the box yet, so we can probably drop this from the default?

**Comment by swiftgist** [comment]
Should this just become an alternate default?  Then, it would serve as an example if somebody is experimenting with bucket style access with one client.

**Comment by theanalyst** [comment]
It could be an alternate default. Don't want to have it as the default default

**Comment by swiftgist** [comment]
Recently ran across setups that use load balancers and want a static `rgw dns name`.  While supported, the .../ceph.conf.d/rgw.conf is technically unique in needing a label.  All other *.conf sections have the label in the ceph.conf.j2 (e.g. mon, osd, mgr, etc.)

This may need an improvement in the README, a default-loadbalancer example or both.
