### ISSUE TITLE
is there any issue connected with ceph repo ?

### ISSUE THREAD

**Issue by IamAliBaba** [SUSE/DeepSea#870]
stage prep dependencies suse: An error was encountered while installing package(s): Zypper command failure: Repository 'ceph-L' is invalid.
[ceph-L|http://download.opensuse.org/repositories/filesystems:/ceph:/luminous/openSUSE_Leap_42.3/] Valid metadata not found at specified URL
Please check if the URIs defined for this repository are pointing to a valid repository.

**Comment by smithfarm** [comment]
This error typically means the repository needs to be refreshed. This can be done automatically, but needs to be enabled. Look at the last column of `zypper lr` ("Refresh"). What does it say for the repo "ceph-L" ?

The command to turn on refresh would be: `zypper modifyrepo --refresh ceph-L` (see "man zypper" for details).

**Comment by smithfarm** [comment]
Since this is a cluster of machines (not just one machine), any change will need to be done on all machines - not just one.

**Comment by IamAliBaba** [comment]
Hello, 
from node machine zypper ref is working fine .

but when im trying to do with deepsea im getting this

**Comment by smithfarm** [comment]
Enable refresh on the repo, on all machines.

**Comment by IamAliBaba** [comment]
ok doing now

**Comment by IamAliBaba** [comment]
the same problem ((

**Comment by IamAliBaba** [comment]
all repos i added have this issue .
but a 2 week ago there isny any

**Comment by IamAliBaba** [comment]
any ideas ?

**Comment by IamAliBaba** [comment]
i'm using 4.4.103-36-default could it connected with it ?

**Comment by IamAliBaba** [comment]
solved, during refresh i set "trust" not "always trust"

thanks for halp
