### ISSUE TITLE
Salt API is failing to authenticate - try 'systemctl restart salt-master': No JSON object could be decoded

### ISSUE THREAD

**Issue by IamAliBaba** [SUSE/DeepSea#871]
any updates?

**Comment by jschmid1** [comment]
Could you please specify your problem by posting logs or providing more information?

**Comment by IamAliBaba** [comment]
Hello thanks for responding.

at first 
i got this 

ceph-admin:~ # nano /etc/salt/master.d/salt-api.conf
ceph-admin:~ # systemctl restart salt-master
ceph-admin:~ # salt-run state.orch ceph.stage.1
[WARNING ] /usr/lib/python2.7/site-packages/salt/client/__init__.py:705: DeprecationWarning: The target type should be passed using the 'tgt_type' argument instead of 'expr_form'. Support for using 'expr_form' will be removed in Salt Fluorine.

salt-api                 : ["Salt API is failing to authenticate - try 'systemctl restart salt-master': No JSON object could be decoded"]
deepsea_minions          : valid
master_minion            : valid
ceph_version             : valid
[ERROR   ] No highstate or sls specified, no execution made
ceph-admin_master:
----------
          ID: salt-api failed
    Function: salt.state
        Name: just.exit
      Result: False
     Comment: No highstate or sls specified, no execution made
     Started: 06:29:51.588800
    Duration: 1.891 ms
     Changes:

Summary for ceph-admin_master
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   1.891 ms
ceph-admin:~ # su salt
ceph-admin:~ #

**Comment by IamAliBaba** [comment]
when i'm changing salt-api port from /etc/salt/master.d/salt-api.conf i could pass this stage and after finish when im trying to connect openattic to the rest api im getting error

i will post it shortly

**Comment by IamAliBaba** [comment]
this is after changing salt-api port from 8000 to 8008

ceph-admin:~ # salt-run state.orch ceph.stage.1
[WARNING ] /usr/lib/python2.7/site-packages/salt/client/__init__.py:705: DeprecationWarning: The target type should be passed using the 'tgt_type' argument instead of 'expr_form'. Support for using 'expr_form' will be removed in Salt Fluorine.

deepsea_minions          : valid
master_minion            : valid
ceph_version             : valid
[WARNING ] All minions are ready
{}
ceph-admin_master:
  Name: minions.ready - Function: salt.runner - Result: Changed Started: - 08:07:43.527206 Duration: 1842.374 ms
  Name: refresh_pillar0 - Function: salt.state - Result: Changed Started: - 08:07:45.370137 Duration: 335.673 ms
  Name: populate.proposals - Function: salt.runner - Result: Changed Started: - 08:07:45.706098 Duration: 6226.053 ms
  Name: proposal.populate - Function: salt.runner - Result: Changed Started: - 08:07:51.932329 Duration: 2484.54 ms

Summary for ceph-admin_master
------------
Succeeded: 4 (changed=4)
Failed:    0
------------
Total states run:     4
Total run time:  10.889 s
ceph-admin:~ #

**Comment by IamAliBaba** [comment]
ceph-admin:~ # salt-api -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/eauth.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/eauth.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/modules.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/modules.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/output.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/output.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/salt-api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/salt-api.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/sharedsecret.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/sharedsecret.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: ceph-admin
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt API
[DEBUG   ] Created pidfile: /var/run/salt-api.pid
[INFO    ] The salt-api is starting up
[INFO    ] Starting rest_cherrypy.start netapi module
[DEBUG   ] Started 'salt.loaded.int.netapi.rest_cherrypy.start' with pid 2687
[DEBUG   ] Process Manager starting!
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[INFO    ] [21/Dec/2017:08:41:21] ENGINE Listening for SIGHUP.
[INFO    ] [21/Dec/2017:08:41:21] ENGINE Listening for SIGTERM.
[INFO    ] [21/Dec/2017:08:41:21] ENGINE Listening for SIGUSR1.
[INFO    ] [21/Dec/2017:08:41:21] ENGINE Bus STARTING
[INFO    ] [21/Dec/2017:08:41:21] ENGINE Started monitor thread '_TimeoutMonitor'.
[ERROR   ] [21/Dec/2017:08:41:26] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7f91b8342990>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 205, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpserver.py", line 168, in start
    ServerAdapter.start(self)
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 170, in start
    wait_for_free_port(*self.bind_addr)
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 438, in wait_for_free_port
    raise IOError("Port %r not free on %r" % (port, host))
IOError: Port 8008 not free on '0.0.0.0'

[ERROR   ] [21/Dec/2017:08:41:26] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 243, in start
    self.publish('start')
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 223, in publish
    raise exc
ChannelFailures: IOError("Port 8008 not free on '0.0.0.0'",)

[INFO    ] [21/Dec/2017:08:41:26] ENGINE Bus STOPPING
[INFO    ] [21/Dec/2017:08:41:26] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8008)) already shut down
[INFO    ] [21/Dec/2017:08:41:26] ENGINE Stopped thread '_TimeoutMonitor'.
[INFO    ] [21/Dec/2017:08:41:26] ENGINE Bus STOPPED
[INFO    ] [21/Dec/2017:08:41:26] ENGINE Bus EXITING
[INFO    ] [21/Dec/2017:08:41:26] ENGINE Bus EXITED
[INFO    ] Process <function start at 0x7f91b83412a8> (2687) died with exit status 70, restarting...
[DEBUG   ] Started 'salt.loaded.int.netapi.rest_cherrypy.start' with pid 2723
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[INFO    ] [21/Dec/2017:08:41:31] ENGINE Listening for SIGHUP.
[INFO    ] [21/Dec/2017:08:41:31] ENGINE Listening for SIGTERM.
[INFO    ] [21/Dec/2017:08:41:31] ENGINE Listening for SIGUSR1.
[INFO    ] [21/Dec/2017:08:41:31] ENGINE Bus STARTING
[INFO    ] [21/Dec/2017:08:41:31] ENGINE Started monitor thread '_TimeoutMonitor'.
^CProcess salt.loaded.int.netapi.rest_cherrypy.start:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/__init__.py", line 98, in start
    cherrypy.quickstart(root, apiopts.get('root_prefix', '/'), conf)
  File "/usr/lib/python2.7/site-packages/cherrypy/__init__.py", line 174, in quickstart
    engine.start()
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 243, in start
    self.publish('start')
  File "/usr/lib/python2.7/site-packages/cherrypy/process/wspbus.py", line 205, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpserver.py", line 168, in start
    ServerAdapter.start(self)
  File "/usr/lib/python2.7/site-packages/cherrypy/process/servers.py", line 170, in start
    wait_for_free_port(*self.bind_addr)

**Comment by IamAliBaba** [comment]
Bug found

salt-2017 is the reason , this error accrue

**Comment by jschmid1** [comment]
ok, closing then
