### ISSUE TITLE
could anyone tell me which release is now stable 0.9 or 0.8.2   

### ISSUE THREAD

**Issue by IamAliBaba** [SUSE/DeepSea#885]
Thanks

**Comment by jschmid1** [comment]
@IamAliBaba 
it's the 0.8.2

Please use our mailinglist to ask questions. This is an issue tracker and not a the right place for general questions.

Register here:
http://lists.suse.com/mailman/listinfo/deepsea-users
for:
deepsea-users@lists.suse.com

**Comment by IamAliBaba** [comment]
sorry.
