### ISSUE TITLE
CephFS data and metadata pools shouldn't use a 1:1 PG count ratio

### ISSUE THREAD

**Issue by ddiss** [SUSE/DeepSea#887]
A static PG count of 128 is used for both the cephfs_metadata and cephfs_data pools created by Deepsea following mds deployment. A default ratio of 4:1 would be more suitable here, as per http://lists.ceph.com/pipermail/ceph-users-ceph.com/2017-March/016966.html .

Ideally Deepsea would take a number of other external metrics into account when calculating the PG count for new pools, i.e. resemble http://ceph.com/pgcalc/.

**Comment by smithfarm** [comment]
See also #536

**Comment by swiftgist** [comment]
I am adding the feature label because I think this touches on more than just CephFS.  I have some thoughts and fears (mainly, the rabbit hole kind).  This is likely less urgent than some of the current issues, yet I do not want to lose it in the noise.
