### ISSUE TITLE
Add debug statements to push.py

### ISSUE THREAD

**Issue by jschmid1** [SUSE/DeepSea#897]
Tracing a bug that was caused by a missing comment in the policy.cfg was not easy, stracktraces were very missleading.

Make debugging easier by adding log.debug statements to:

https://github.com/SUSE/DeepSea/blob/master/srv/modules/runners/push.py#L247

**Comment by denisok** [comment]
Just for the reference:
https://github.com/openSUSE/vagrant-ceph/issues/6
