### ISSUE TITLE
Out with ntpd, in with chrony?

### ISSUE THREAD

**Issue by smithfarm** [SUSE/DeepSea#913]
RHEL, Ubuntu, and SUSE are migrating to chrony. According to Fabian, SLE15 will have ntpd only via the "Legacy" module.

DeepSea will need to install/configure chrony instead of ntpd.

Upstream tracker: https://tracker.ceph.com/issues/22751

**Comment by swiftgist** [comment]
Same as #596

**Comment by swiftgist** [comment]
completed in #930
