### ISSUE TITLE
Please add example about how to set the deepsea grain also in deepsea_minions.sls

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/DeepSea#924]
When we start a stage without setting the deepsea grain the orchestration complains about this error with a hint to deepsea_minions.sls. Then an admin will look into that sls file and is pointed to the man page.

In case we could have a comment in deepsea_minions.sls about how to set the grain this would enhance usability a bit.

So could we add an example like "salt '<FQDN of ceph target host / minion id>' grains.set deepsea default" as commeted example to deepsea_minions.sls ?

**Comment by swiftgist** [comment]
It may be better to improve the first message to say "see man deepsea minions".  Likely better to have two arrows pointing to the same example, then have two examples that will eventually diverge.

**Comment by Martin-Weiss** [comment]
Sure - yes - pointing to the man page in the error message might also help.

**Comment by jschmid1** [comment]
> It may be better to improve the first message to say "see man deepsea minions". Likely better to have two arrows pointing to the same example, then have two examples that will eventually diverge.

That's probably the right way to go. The workflow would be:

Run -> get the error message -> man deepsea-minions -> add the grain -> view the file -> run stage again.
