### ISSUE TITLE
ceph tell bench

### ISSUE THREAD

**Issue by swiftgist** [SUSE/DeepSea#943]
This benchmarking of a single OSD can be useful for finding poorly performing OSDs, but is a bit cumbersome to use if you have hundreds.

This could use a little research to see how much can be done in parallel and then decide if a salt-runner calling a module is the best approach.  For a generic 'check all OSDs', results similar to net.iperf would be nice (i.e. show the two fastest, two slowest).  

The runner should likely handle an argument or list too.

**Comment by jan--f** [comment]
You mean something like [this](https://github.com/SUSE/DeepSea/blob/master/srv/modules/runners/benchmark.py#L253). It doesn't do anyhting in parallel (yet) but the rest is there.

**Comment by swiftgist** [comment]
Completely slipped my mind.... benchmarks could use some TLC and advertising. :)  Closing this one.
