### ISSUE TITLE
pillar data and proposals should use "user-friendlier" names for disks

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/DeepSea#952]
When we have to deal with disks in a server for OSDs there are three different names available in /dev/disk/by-id - i.e.:

```
lrwxrwxrwx 1 root root    9 Feb 20 13:16 scsi-35000cca2443c7c80 -> ../../sdf
lrwxrwxrwx 1 root root    9 Feb 20 13:16 scsi-SHGST_HUS726040AL5210_N8H2870Z -> ../../sdf
lrwxrwxrwx 1 root root    9 Feb 20 13:16 wwn-0x5000cca2443c7c80 -> ../../sdf

```

At the moment it seems that the first one - in the above example "scsi-35000cca2443c7c80" is used - but that number is most often not very user friendly as it does not allow to identify the vendor or the disk serial number directly.

The other name "scsi-SHGST_HUS726040AL5210_N8H2870Z" would be much better as this has the disk type "HUS726040AL5210" and the serial number "N8H2870Z".

Would it be possible to adjust DeepSea to use the name "scsi-SHGST_HUS726040AL5210_N8H2870Z"?

**Comment by abonillasuse** [comment]
Ceph uses by-partuuid/ - perhaps we can standardize?

**Comment by Martin-Weiss** [comment]
There is no by-partuuid for disks that do not have a partition table - so unfortunately this can not be used "before" OSDs are deployed.
