### ISSUE TITLE
Stop migration if custom crushmap is detected

### ISSUE THREAD

**Issue by jschmid1** [SUSE/DeepSea#975]
Currently we do not support the migration of filestore to bluestore OSDs when a custom crushmap is used.

Detect it and bail out is the currently the best solution we can offer.

**Comment by Martin-Weiss** [comment]
Hm and how should someone do the filestore -> bluestore migration, then?

Can´t we document where and with which weight an OSD is located in the crushmap and then re-add it to the same place with the same weight?

**Comment by jschmid1** [comment]
that's the plan. We don't have that automated _now_.

**Comment by jschmid1** [comment]
done with #1216
