### ISSUE TITLE
python abi

### ISSUE THREAD

**Issue by swiftgist** [SUSE/DeepSea#993]
### Description of Issue/Question

With the latest master, a locally built rpm gains the requirement

python(abi) = 3.4

The result is that the rpm installation will fail on a SLE15 system unless --nodeps is used.

The requirement is tied to the deepsea cli.  The python 3.4 comes from the host system, but the cli should not really need to be hardcoded to a specific abi.

**Comment by rjfd** [comment]
>  The python 3.4 comes from the host system

Are you referring to the OBS host that builds the RPM?

**Comment by swiftgist** [comment]
No, I was building locally.  But even in the OBS case, if I as a user had been using DeepSea and my python version changes from 3.X to 3.Y, I would expect something as portable as python to keep working.  I know this isn't an api >= 3.4 requirement, but it seems like it should be.

Also, pysetup seemed to support the --no-autoreq at one point.

**Comment by lyzenghq** [comment]
I also encountered this problem, and my deepsea does not work properly.

**Comment by jschmid1** [comment]
Can be circumvented by building with the correct python abi
